// Code generated by ent, DO NOT EDIT.

package usertag

import (
	"go-wind-uba/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldDeletedBy, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldUserID, v))
}

// TagID applies equality check predicate on the "tag_id" field. It's identical to TagIDEQ.
func TagID(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldTagID, v))
}

// TagValue applies equality check predicate on the "tag_value" field. It's identical to TagValueEQ.
func TagValue(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldTagValue, v))
}

// ValueLabel applies equality check predicate on the "value_label" field. It's identical to ValueLabelEQ.
func ValueLabel(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldValueLabel, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldConfidence, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldSource, v))
}

// SourceRuleID applies equality check predicate on the "source_rule_id" field. It's identical to SourceRuleIDEQ.
func SourceRuleID(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldSourceRuleID, v))
}

// EffectiveTime applies equality check predicate on the "effective_time" field. It's identical to EffectiveTimeEQ.
func EffectiveTime(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldEffectiveTime, v))
}

// ExpireTime applies equality check predicate on the "expire_time" field. It's identical to ExpireTimeEQ.
func ExpireTime(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldExpireTime, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldIsActive, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldTenantID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldDeletedBy))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldUserID))
}

// TagIDEQ applies the EQ predicate on the "tag_id" field.
func TagIDEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldTagID, v))
}

// TagIDNEQ applies the NEQ predicate on the "tag_id" field.
func TagIDNEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldTagID, v))
}

// TagIDIn applies the In predicate on the "tag_id" field.
func TagIDIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldTagID, vs...))
}

// TagIDNotIn applies the NotIn predicate on the "tag_id" field.
func TagIDNotIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldTagID, vs...))
}

// TagIDGT applies the GT predicate on the "tag_id" field.
func TagIDGT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldTagID, v))
}

// TagIDGTE applies the GTE predicate on the "tag_id" field.
func TagIDGTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldTagID, v))
}

// TagIDLT applies the LT predicate on the "tag_id" field.
func TagIDLT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldTagID, v))
}

// TagIDLTE applies the LTE predicate on the "tag_id" field.
func TagIDLTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldTagID, v))
}

// TagIDIsNil applies the IsNil predicate on the "tag_id" field.
func TagIDIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldTagID))
}

// TagIDNotNil applies the NotNil predicate on the "tag_id" field.
func TagIDNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldTagID))
}

// TagValueEQ applies the EQ predicate on the "tag_value" field.
func TagValueEQ(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldTagValue, v))
}

// TagValueNEQ applies the NEQ predicate on the "tag_value" field.
func TagValueNEQ(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldTagValue, v))
}

// TagValueIn applies the In predicate on the "tag_value" field.
func TagValueIn(vs ...string) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldTagValue, vs...))
}

// TagValueNotIn applies the NotIn predicate on the "tag_value" field.
func TagValueNotIn(vs ...string) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldTagValue, vs...))
}

// TagValueGT applies the GT predicate on the "tag_value" field.
func TagValueGT(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldTagValue, v))
}

// TagValueGTE applies the GTE predicate on the "tag_value" field.
func TagValueGTE(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldTagValue, v))
}

// TagValueLT applies the LT predicate on the "tag_value" field.
func TagValueLT(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldTagValue, v))
}

// TagValueLTE applies the LTE predicate on the "tag_value" field.
func TagValueLTE(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldTagValue, v))
}

// TagValueContains applies the Contains predicate on the "tag_value" field.
func TagValueContains(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldContains(FieldTagValue, v))
}

// TagValueHasPrefix applies the HasPrefix predicate on the "tag_value" field.
func TagValueHasPrefix(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldHasPrefix(FieldTagValue, v))
}

// TagValueHasSuffix applies the HasSuffix predicate on the "tag_value" field.
func TagValueHasSuffix(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldHasSuffix(FieldTagValue, v))
}

// TagValueEqualFold applies the EqualFold predicate on the "tag_value" field.
func TagValueEqualFold(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldEqualFold(FieldTagValue, v))
}

// TagValueContainsFold applies the ContainsFold predicate on the "tag_value" field.
func TagValueContainsFold(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldContainsFold(FieldTagValue, v))
}

// ValueLabelEQ applies the EQ predicate on the "value_label" field.
func ValueLabelEQ(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldValueLabel, v))
}

// ValueLabelNEQ applies the NEQ predicate on the "value_label" field.
func ValueLabelNEQ(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldValueLabel, v))
}

// ValueLabelIn applies the In predicate on the "value_label" field.
func ValueLabelIn(vs ...string) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldValueLabel, vs...))
}

// ValueLabelNotIn applies the NotIn predicate on the "value_label" field.
func ValueLabelNotIn(vs ...string) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldValueLabel, vs...))
}

// ValueLabelGT applies the GT predicate on the "value_label" field.
func ValueLabelGT(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldValueLabel, v))
}

// ValueLabelGTE applies the GTE predicate on the "value_label" field.
func ValueLabelGTE(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldValueLabel, v))
}

// ValueLabelLT applies the LT predicate on the "value_label" field.
func ValueLabelLT(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldValueLabel, v))
}

// ValueLabelLTE applies the LTE predicate on the "value_label" field.
func ValueLabelLTE(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldValueLabel, v))
}

// ValueLabelContains applies the Contains predicate on the "value_label" field.
func ValueLabelContains(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldContains(FieldValueLabel, v))
}

// ValueLabelHasPrefix applies the HasPrefix predicate on the "value_label" field.
func ValueLabelHasPrefix(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldHasPrefix(FieldValueLabel, v))
}

// ValueLabelHasSuffix applies the HasSuffix predicate on the "value_label" field.
func ValueLabelHasSuffix(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldHasSuffix(FieldValueLabel, v))
}

// ValueLabelIsNil applies the IsNil predicate on the "value_label" field.
func ValueLabelIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldValueLabel))
}

// ValueLabelNotNil applies the NotNil predicate on the "value_label" field.
func ValueLabelNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldValueLabel))
}

// ValueLabelEqualFold applies the EqualFold predicate on the "value_label" field.
func ValueLabelEqualFold(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldEqualFold(FieldValueLabel, v))
}

// ValueLabelContainsFold applies the ContainsFold predicate on the "value_label" field.
func ValueLabelContainsFold(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldContainsFold(FieldValueLabel, v))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldConfidence, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.UserTag {
	return predicate.UserTag(sql.FieldContainsFold(FieldSource, v))
}

// SourceRuleIDEQ applies the EQ predicate on the "source_rule_id" field.
func SourceRuleIDEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldSourceRuleID, v))
}

// SourceRuleIDNEQ applies the NEQ predicate on the "source_rule_id" field.
func SourceRuleIDNEQ(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldSourceRuleID, v))
}

// SourceRuleIDIn applies the In predicate on the "source_rule_id" field.
func SourceRuleIDIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldSourceRuleID, vs...))
}

// SourceRuleIDNotIn applies the NotIn predicate on the "source_rule_id" field.
func SourceRuleIDNotIn(vs ...uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldSourceRuleID, vs...))
}

// SourceRuleIDGT applies the GT predicate on the "source_rule_id" field.
func SourceRuleIDGT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldSourceRuleID, v))
}

// SourceRuleIDGTE applies the GTE predicate on the "source_rule_id" field.
func SourceRuleIDGTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldSourceRuleID, v))
}

// SourceRuleIDLT applies the LT predicate on the "source_rule_id" field.
func SourceRuleIDLT(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldSourceRuleID, v))
}

// SourceRuleIDLTE applies the LTE predicate on the "source_rule_id" field.
func SourceRuleIDLTE(v uint32) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldSourceRuleID, v))
}

// SourceRuleIDIsNil applies the IsNil predicate on the "source_rule_id" field.
func SourceRuleIDIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldSourceRuleID))
}

// SourceRuleIDNotNil applies the NotNil predicate on the "source_rule_id" field.
func SourceRuleIDNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldSourceRuleID))
}

// EffectiveTimeEQ applies the EQ predicate on the "effective_time" field.
func EffectiveTimeEQ(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldEffectiveTime, v))
}

// EffectiveTimeNEQ applies the NEQ predicate on the "effective_time" field.
func EffectiveTimeNEQ(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldEffectiveTime, v))
}

// EffectiveTimeIn applies the In predicate on the "effective_time" field.
func EffectiveTimeIn(vs ...time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldEffectiveTime, vs...))
}

// EffectiveTimeNotIn applies the NotIn predicate on the "effective_time" field.
func EffectiveTimeNotIn(vs ...time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldEffectiveTime, vs...))
}

// EffectiveTimeGT applies the GT predicate on the "effective_time" field.
func EffectiveTimeGT(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldEffectiveTime, v))
}

// EffectiveTimeGTE applies the GTE predicate on the "effective_time" field.
func EffectiveTimeGTE(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldEffectiveTime, v))
}

// EffectiveTimeLT applies the LT predicate on the "effective_time" field.
func EffectiveTimeLT(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldEffectiveTime, v))
}

// EffectiveTimeLTE applies the LTE predicate on the "effective_time" field.
func EffectiveTimeLTE(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldEffectiveTime, v))
}

// EffectiveTimeIsNil applies the IsNil predicate on the "effective_time" field.
func EffectiveTimeIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldEffectiveTime))
}

// EffectiveTimeNotNil applies the NotNil predicate on the "effective_time" field.
func EffectiveTimeNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldEffectiveTime))
}

// ExpireTimeEQ applies the EQ predicate on the "expire_time" field.
func ExpireTimeEQ(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldExpireTime, v))
}

// ExpireTimeNEQ applies the NEQ predicate on the "expire_time" field.
func ExpireTimeNEQ(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldExpireTime, v))
}

// ExpireTimeIn applies the In predicate on the "expire_time" field.
func ExpireTimeIn(vs ...time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldIn(FieldExpireTime, vs...))
}

// ExpireTimeNotIn applies the NotIn predicate on the "expire_time" field.
func ExpireTimeNotIn(vs ...time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldNotIn(FieldExpireTime, vs...))
}

// ExpireTimeGT applies the GT predicate on the "expire_time" field.
func ExpireTimeGT(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldGT(FieldExpireTime, v))
}

// ExpireTimeGTE applies the GTE predicate on the "expire_time" field.
func ExpireTimeGTE(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldGTE(FieldExpireTime, v))
}

// ExpireTimeLT applies the LT predicate on the "expire_time" field.
func ExpireTimeLT(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldLT(FieldExpireTime, v))
}

// ExpireTimeLTE applies the LTE predicate on the "expire_time" field.
func ExpireTimeLTE(v time.Time) predicate.UserTag {
	return predicate.UserTag(sql.FieldLTE(FieldExpireTime, v))
}

// ExpireTimeIsNil applies the IsNil predicate on the "expire_time" field.
func ExpireTimeIsNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldIsNull(FieldExpireTime))
}

// ExpireTimeNotNil applies the NotNil predicate on the "expire_time" field.
func ExpireTimeNotNil() predicate.UserTag {
	return predicate.UserTag(sql.FieldNotNull(FieldExpireTime))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.UserTag {
	return predicate.UserTag(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.UserTag {
	return predicate.UserTag(sql.FieldNEQ(FieldIsActive, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserTag) predicate.UserTag {
	return predicate.UserTag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserTag) predicate.UserTag {
	return predicate.UserTag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserTag) predicate.UserTag {
	return predicate.UserTag(sql.NotPredicates(p))
}
