// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-uba/app/core/service/internal/data/ent/application"
	"go-wind-uba/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ApplicationUpdate is the builder for updating Application entities.
type ApplicationUpdate struct {
	config
	hooks     []Hook
	mutation  *ApplicationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ApplicationUpdate builder.
func (_u *ApplicationUpdate) Where(ps ...predicate.Application) *ApplicationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApplicationUpdate) SetUpdatedAt(v time.Time) *ApplicationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableUpdatedAt(v *time.Time) *ApplicationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ApplicationUpdate) ClearUpdatedAt() *ApplicationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ApplicationUpdate) SetDeletedAt(v time.Time) *ApplicationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableDeletedAt(v *time.Time) *ApplicationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ApplicationUpdate) ClearDeletedAt() *ApplicationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ApplicationUpdate) SetCreatedBy(v uint32) *ApplicationUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableCreatedBy(v *uint32) *ApplicationUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ApplicationUpdate) AddCreatedBy(v int32) *ApplicationUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ApplicationUpdate) ClearCreatedBy() *ApplicationUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ApplicationUpdate) SetUpdatedBy(v uint32) *ApplicationUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableUpdatedBy(v *uint32) *ApplicationUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ApplicationUpdate) AddUpdatedBy(v int32) *ApplicationUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ApplicationUpdate) ClearUpdatedBy() *ApplicationUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ApplicationUpdate) SetDeletedBy(v uint32) *ApplicationUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableDeletedBy(v *uint32) *ApplicationUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ApplicationUpdate) AddDeletedBy(v int32) *ApplicationUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ApplicationUpdate) ClearDeletedBy() *ApplicationUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *ApplicationUpdate) SetName(v string) *ApplicationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableName(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ApplicationUpdate) ClearName() *ApplicationUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *ApplicationUpdate) SetAppID(v string) *ApplicationUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableAppID(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *ApplicationUpdate) ClearAppID() *ApplicationUpdate {
	_u.mutation.ClearAppID()
	return _u
}

// SetAppKey sets the "app_key" field.
func (_u *ApplicationUpdate) SetAppKey(v string) *ApplicationUpdate {
	_u.mutation.SetAppKey(v)
	return _u
}

// SetNillableAppKey sets the "app_key" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableAppKey(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetAppKey(*v)
	}
	return _u
}

// ClearAppKey clears the value of the "app_key" field.
func (_u *ApplicationUpdate) ClearAppKey() *ApplicationUpdate {
	_u.mutation.ClearAppKey()
	return _u
}

// SetAppSecret sets the "app_secret" field.
func (_u *ApplicationUpdate) SetAppSecret(v string) *ApplicationUpdate {
	_u.mutation.SetAppSecret(v)
	return _u
}

// SetNillableAppSecret sets the "app_secret" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableAppSecret(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetAppSecret(*v)
	}
	return _u
}

// ClearAppSecret clears the value of the "app_secret" field.
func (_u *ApplicationUpdate) ClearAppSecret() *ApplicationUpdate {
	_u.mutation.ClearAppSecret()
	return _u
}

// SetType sets the "type" field.
func (_u *ApplicationUpdate) SetType(v string) *ApplicationUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableType(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *ApplicationUpdate) ClearType() *ApplicationUpdate {
	_u.mutation.ClearType()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApplicationUpdate) SetStatus(v application.Status) *ApplicationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableStatus(v *application.Status) *ApplicationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ApplicationUpdate) ClearStatus() *ApplicationUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetPlatforms sets the "platforms" field.
func (_u *ApplicationUpdate) SetPlatforms(v []string) *ApplicationUpdate {
	_u.mutation.SetPlatforms(v)
	return _u
}

// AppendPlatforms appends value to the "platforms" field.
func (_u *ApplicationUpdate) AppendPlatforms(v []string) *ApplicationUpdate {
	_u.mutation.AppendPlatforms(v)
	return _u
}

// ClearPlatforms clears the value of the "platforms" field.
func (_u *ApplicationUpdate) ClearPlatforms() *ApplicationUpdate {
	_u.mutation.ClearPlatforms()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ApplicationUpdate) SetRemark(v string) *ApplicationUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableRemark(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ApplicationUpdate) ClearRemark() *ApplicationUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetDesensitize sets the "desensitize" field.
func (_u *ApplicationUpdate) SetDesensitize(v bool) *ApplicationUpdate {
	_u.mutation.SetDesensitize(v)
	return _u
}

// SetNillableDesensitize sets the "desensitize" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableDesensitize(v *bool) *ApplicationUpdate {
	if v != nil {
		_u.SetDesensitize(*v)
	}
	return _u
}

// ClearDesensitize clears the value of the "desensitize" field.
func (_u *ApplicationUpdate) ClearDesensitize() *ApplicationUpdate {
	_u.mutation.ClearDesensitize()
	return _u
}

// SetWebhookURL sets the "webhook_url" field.
func (_u *ApplicationUpdate) SetWebhookURL(v string) *ApplicationUpdate {
	_u.mutation.SetWebhookURL(v)
	return _u
}

// SetNillableWebhookURL sets the "webhook_url" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableWebhookURL(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetWebhookURL(*v)
	}
	return _u
}

// ClearWebhookURL clears the value of the "webhook_url" field.
func (_u *ApplicationUpdate) ClearWebhookURL() *ApplicationUpdate {
	_u.mutation.ClearWebhookURL()
	return _u
}

// SetWebhookSecret sets the "webhook_secret" field.
func (_u *ApplicationUpdate) SetWebhookSecret(v string) *ApplicationUpdate {
	_u.mutation.SetWebhookSecret(v)
	return _u
}

// SetNillableWebhookSecret sets the "webhook_secret" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableWebhookSecret(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetWebhookSecret(*v)
	}
	return _u
}

// ClearWebhookSecret clears the value of the "webhook_secret" field.
func (_u *ApplicationUpdate) ClearWebhookSecret() *ApplicationUpdate {
	_u.mutation.ClearWebhookSecret()
	return _u
}

// Mutation returns the ApplicationMutation object of the builder.
func (_u *ApplicationUpdate) Mutation() *ApplicationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApplicationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApplicationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApplicationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApplicationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApplicationUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := application.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Application.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppID(); ok {
		if err := application.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "Application.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := application.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Application.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ApplicationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ApplicationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ApplicationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(application.Table, application.Columns, sqlgraph.NewFieldSpec(application.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(application.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(application.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(application.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(application.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(application.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(application.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(application.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(application.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(application.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(application.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(application.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(application.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(application.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(application.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(application.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(application.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(application.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(application.FieldAppID, field.TypeString, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(application.FieldAppID, field.TypeString)
	}
	if value, ok := _u.mutation.AppKey(); ok {
		_spec.SetField(application.FieldAppKey, field.TypeString, value)
	}
	if _u.mutation.AppKeyCleared() {
		_spec.ClearField(application.FieldAppKey, field.TypeString)
	}
	if value, ok := _u.mutation.AppSecret(); ok {
		_spec.SetField(application.FieldAppSecret, field.TypeString, value)
	}
	if _u.mutation.AppSecretCleared() {
		_spec.ClearField(application.FieldAppSecret, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(application.FieldType, field.TypeString, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(application.FieldType, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(application.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(application.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.Platforms(); ok {
		_spec.SetField(application.FieldPlatforms, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlatforms(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, application.FieldPlatforms, value)
		})
	}
	if _u.mutation.PlatformsCleared() {
		_spec.ClearField(application.FieldPlatforms, field.TypeJSON)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(application.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(application.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Desensitize(); ok {
		_spec.SetField(application.FieldDesensitize, field.TypeBool, value)
	}
	if _u.mutation.DesensitizeCleared() {
		_spec.ClearField(application.FieldDesensitize, field.TypeBool)
	}
	if value, ok := _u.mutation.WebhookURL(); ok {
		_spec.SetField(application.FieldWebhookURL, field.TypeString, value)
	}
	if _u.mutation.WebhookURLCleared() {
		_spec.ClearField(application.FieldWebhookURL, field.TypeString)
	}
	if value, ok := _u.mutation.WebhookSecret(); ok {
		_spec.SetField(application.FieldWebhookSecret, field.TypeString, value)
	}
	if _u.mutation.WebhookSecretCleared() {
		_spec.ClearField(application.FieldWebhookSecret, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{application.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApplicationUpdateOne is the builder for updating a single Application entity.
type ApplicationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ApplicationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApplicationUpdateOne) SetUpdatedAt(v time.Time) *ApplicationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableUpdatedAt(v *time.Time) *ApplicationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ApplicationUpdateOne) ClearUpdatedAt() *ApplicationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ApplicationUpdateOne) SetDeletedAt(v time.Time) *ApplicationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableDeletedAt(v *time.Time) *ApplicationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ApplicationUpdateOne) ClearDeletedAt() *ApplicationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ApplicationUpdateOne) SetCreatedBy(v uint32) *ApplicationUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableCreatedBy(v *uint32) *ApplicationUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ApplicationUpdateOne) AddCreatedBy(v int32) *ApplicationUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ApplicationUpdateOne) ClearCreatedBy() *ApplicationUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ApplicationUpdateOne) SetUpdatedBy(v uint32) *ApplicationUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableUpdatedBy(v *uint32) *ApplicationUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ApplicationUpdateOne) AddUpdatedBy(v int32) *ApplicationUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ApplicationUpdateOne) ClearUpdatedBy() *ApplicationUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ApplicationUpdateOne) SetDeletedBy(v uint32) *ApplicationUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableDeletedBy(v *uint32) *ApplicationUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ApplicationUpdateOne) AddDeletedBy(v int32) *ApplicationUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ApplicationUpdateOne) ClearDeletedBy() *ApplicationUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *ApplicationUpdateOne) SetName(v string) *ApplicationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableName(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ApplicationUpdateOne) ClearName() *ApplicationUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *ApplicationUpdateOne) SetAppID(v string) *ApplicationUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableAppID(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *ApplicationUpdateOne) ClearAppID() *ApplicationUpdateOne {
	_u.mutation.ClearAppID()
	return _u
}

// SetAppKey sets the "app_key" field.
func (_u *ApplicationUpdateOne) SetAppKey(v string) *ApplicationUpdateOne {
	_u.mutation.SetAppKey(v)
	return _u
}

// SetNillableAppKey sets the "app_key" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableAppKey(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetAppKey(*v)
	}
	return _u
}

// ClearAppKey clears the value of the "app_key" field.
func (_u *ApplicationUpdateOne) ClearAppKey() *ApplicationUpdateOne {
	_u.mutation.ClearAppKey()
	return _u
}

// SetAppSecret sets the "app_secret" field.
func (_u *ApplicationUpdateOne) SetAppSecret(v string) *ApplicationUpdateOne {
	_u.mutation.SetAppSecret(v)
	return _u
}

// SetNillableAppSecret sets the "app_secret" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableAppSecret(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetAppSecret(*v)
	}
	return _u
}

// ClearAppSecret clears the value of the "app_secret" field.
func (_u *ApplicationUpdateOne) ClearAppSecret() *ApplicationUpdateOne {
	_u.mutation.ClearAppSecret()
	return _u
}

// SetType sets the "type" field.
func (_u *ApplicationUpdateOne) SetType(v string) *ApplicationUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableType(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *ApplicationUpdateOne) ClearType() *ApplicationUpdateOne {
	_u.mutation.ClearType()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApplicationUpdateOne) SetStatus(v application.Status) *ApplicationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableStatus(v *application.Status) *ApplicationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ApplicationUpdateOne) ClearStatus() *ApplicationUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetPlatforms sets the "platforms" field.
func (_u *ApplicationUpdateOne) SetPlatforms(v []string) *ApplicationUpdateOne {
	_u.mutation.SetPlatforms(v)
	return _u
}

// AppendPlatforms appends value to the "platforms" field.
func (_u *ApplicationUpdateOne) AppendPlatforms(v []string) *ApplicationUpdateOne {
	_u.mutation.AppendPlatforms(v)
	return _u
}

// ClearPlatforms clears the value of the "platforms" field.
func (_u *ApplicationUpdateOne) ClearPlatforms() *ApplicationUpdateOne {
	_u.mutation.ClearPlatforms()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ApplicationUpdateOne) SetRemark(v string) *ApplicationUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableRemark(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ApplicationUpdateOne) ClearRemark() *ApplicationUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetDesensitize sets the "desensitize" field.
func (_u *ApplicationUpdateOne) SetDesensitize(v bool) *ApplicationUpdateOne {
	_u.mutation.SetDesensitize(v)
	return _u
}

// SetNillableDesensitize sets the "desensitize" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableDesensitize(v *bool) *ApplicationUpdateOne {
	if v != nil {
		_u.SetDesensitize(*v)
	}
	return _u
}

// ClearDesensitize clears the value of the "desensitize" field.
func (_u *ApplicationUpdateOne) ClearDesensitize() *ApplicationUpdateOne {
	_u.mutation.ClearDesensitize()
	return _u
}

// SetWebhookURL sets the "webhook_url" field.
func (_u *ApplicationUpdateOne) SetWebhookURL(v string) *ApplicationUpdateOne {
	_u.mutation.SetWebhookURL(v)
	return _u
}

// SetNillableWebhookURL sets the "webhook_url" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableWebhookURL(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetWebhookURL(*v)
	}
	return _u
}

// ClearWebhookURL clears the value of the "webhook_url" field.
func (_u *ApplicationUpdateOne) ClearWebhookURL() *ApplicationUpdateOne {
	_u.mutation.ClearWebhookURL()
	return _u
}

// SetWebhookSecret sets the "webhook_secret" field.
func (_u *ApplicationUpdateOne) SetWebhookSecret(v string) *ApplicationUpdateOne {
	_u.mutation.SetWebhookSecret(v)
	return _u
}

// SetNillableWebhookSecret sets the "webhook_secret" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableWebhookSecret(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetWebhookSecret(*v)
	}
	return _u
}

// ClearWebhookSecret clears the value of the "webhook_secret" field.
func (_u *ApplicationUpdateOne) ClearWebhookSecret() *ApplicationUpdateOne {
	_u.mutation.ClearWebhookSecret()
	return _u
}

// Mutation returns the ApplicationMutation object of the builder.
func (_u *ApplicationUpdateOne) Mutation() *ApplicationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ApplicationUpdate builder.
func (_u *ApplicationUpdateOne) Where(ps ...predicate.Application) *ApplicationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApplicationUpdateOne) Select(field string, fields ...string) *ApplicationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Application entity.
func (_u *ApplicationUpdateOne) Save(ctx context.Context) (*Application, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApplicationUpdateOne) SaveX(ctx context.Context) *Application {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApplicationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApplicationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApplicationUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := application.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Application.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppID(); ok {
		if err := application.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "Application.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := application.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Application.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ApplicationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ApplicationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ApplicationUpdateOne) sqlSave(ctx context.Context) (_node *Application, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(application.Table, application.Columns, sqlgraph.NewFieldSpec(application.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Application.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, application.FieldID)
		for _, f := range fields {
			if !application.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != application.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(application.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(application.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(application.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(application.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(application.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(application.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(application.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(application.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(application.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(application.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(application.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(application.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(application.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(application.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(application.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(application.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(application.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(application.FieldAppID, field.TypeString, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(application.FieldAppID, field.TypeString)
	}
	if value, ok := _u.mutation.AppKey(); ok {
		_spec.SetField(application.FieldAppKey, field.TypeString, value)
	}
	if _u.mutation.AppKeyCleared() {
		_spec.ClearField(application.FieldAppKey, field.TypeString)
	}
	if value, ok := _u.mutation.AppSecret(); ok {
		_spec.SetField(application.FieldAppSecret, field.TypeString, value)
	}
	if _u.mutation.AppSecretCleared() {
		_spec.ClearField(application.FieldAppSecret, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(application.FieldType, field.TypeString, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(application.FieldType, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(application.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(application.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.Platforms(); ok {
		_spec.SetField(application.FieldPlatforms, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlatforms(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, application.FieldPlatforms, value)
		})
	}
	if _u.mutation.PlatformsCleared() {
		_spec.ClearField(application.FieldPlatforms, field.TypeJSON)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(application.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(application.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Desensitize(); ok {
		_spec.SetField(application.FieldDesensitize, field.TypeBool, value)
	}
	if _u.mutation.DesensitizeCleared() {
		_spec.ClearField(application.FieldDesensitize, field.TypeBool)
	}
	if value, ok := _u.mutation.WebhookURL(); ok {
		_spec.SetField(application.FieldWebhookURL, field.TypeString, value)
	}
	if _u.mutation.WebhookURLCleared() {
		_spec.ClearField(application.FieldWebhookURL, field.TypeString)
	}
	if value, ok := _u.mutation.WebhookSecret(); ok {
		_spec.SetField(application.FieldWebhookSecret, field.TypeString, value)
	}
	if _u.mutation.WebhookSecretCleared() {
		_spec.ClearField(application.FieldWebhookSecret, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Application{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{application.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
