// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-uba/app/core/service/internal/data/ent/dicttype"
	"go-wind-uba/app/core/service/internal/data/ent/dicttypei18n"
	"go-wind-uba/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictTypeI18nUpdate is the builder for updating DictTypeI18n entities.
type DictTypeI18nUpdate struct {
	config
	hooks     []Hook
	mutation  *DictTypeI18nMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DictTypeI18nUpdate builder.
func (_u *DictTypeI18nUpdate) Where(ps ...predicate.DictTypeI18n) *DictTypeI18nUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictTypeI18nUpdate) SetUpdatedAt(v time.Time) *DictTypeI18nUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DictTypeI18nUpdate) SetNillableUpdatedAt(v *time.Time) *DictTypeI18nUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DictTypeI18nUpdate) ClearUpdatedAt() *DictTypeI18nUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictTypeI18nUpdate) SetDeletedAt(v time.Time) *DictTypeI18nUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictTypeI18nUpdate) SetNillableDeletedAt(v *time.Time) *DictTypeI18nUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictTypeI18nUpdate) ClearDeletedAt() *DictTypeI18nUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DictTypeI18nUpdate) SetCreatedBy(v uint32) *DictTypeI18nUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DictTypeI18nUpdate) SetNillableCreatedBy(v *uint32) *DictTypeI18nUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DictTypeI18nUpdate) AddCreatedBy(v int32) *DictTypeI18nUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DictTypeI18nUpdate) ClearCreatedBy() *DictTypeI18nUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *DictTypeI18nUpdate) SetUpdatedBy(v uint32) *DictTypeI18nUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *DictTypeI18nUpdate) SetNillableUpdatedBy(v *uint32) *DictTypeI18nUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *DictTypeI18nUpdate) AddUpdatedBy(v int32) *DictTypeI18nUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *DictTypeI18nUpdate) ClearUpdatedBy() *DictTypeI18nUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *DictTypeI18nUpdate) SetDeletedBy(v uint32) *DictTypeI18nUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *DictTypeI18nUpdate) SetNillableDeletedBy(v *uint32) *DictTypeI18nUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *DictTypeI18nUpdate) AddDeletedBy(v int32) *DictTypeI18nUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *DictTypeI18nUpdate) ClearDeletedBy() *DictTypeI18nUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DictTypeI18nUpdate) SetDescription(v string) *DictTypeI18nUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DictTypeI18nUpdate) SetNillableDescription(v *string) *DictTypeI18nUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DictTypeI18nUpdate) ClearDescription() *DictTypeI18nUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTypeName sets the "type_name" field.
func (_u *DictTypeI18nUpdate) SetTypeName(v string) *DictTypeI18nUpdate {
	_u.mutation.SetTypeName(v)
	return _u
}

// SetNillableTypeName sets the "type_name" field if the given value is not nil.
func (_u *DictTypeI18nUpdate) SetNillableTypeName(v *string) *DictTypeI18nUpdate {
	if v != nil {
		_u.SetTypeName(*v)
	}
	return _u
}

// ClearTypeName clears the value of the "type_name" field.
func (_u *DictTypeI18nUpdate) ClearTypeName() *DictTypeI18nUpdate {
	_u.mutation.ClearTypeName()
	return _u
}

// SetDictTypeID sets the "dict_type" edge to the DictType entity by ID.
func (_u *DictTypeI18nUpdate) SetDictTypeID(id uint32) *DictTypeI18nUpdate {
	_u.mutation.SetDictTypeID(id)
	return _u
}

// SetNillableDictTypeID sets the "dict_type" edge to the DictType entity by ID if the given value is not nil.
func (_u *DictTypeI18nUpdate) SetNillableDictTypeID(id *uint32) *DictTypeI18nUpdate {
	if id != nil {
		_u = _u.SetDictTypeID(*id)
	}
	return _u
}

// SetDictType sets the "dict_type" edge to the DictType entity.
func (_u *DictTypeI18nUpdate) SetDictType(v *DictType) *DictTypeI18nUpdate {
	return _u.SetDictTypeID(v.ID)
}

// Mutation returns the DictTypeI18nMutation object of the builder.
func (_u *DictTypeI18nUpdate) Mutation() *DictTypeI18nMutation {
	return _u.mutation
}

// ClearDictType clears the "dict_type" edge to the DictType entity.
func (_u *DictTypeI18nUpdate) ClearDictType() *DictTypeI18nUpdate {
	_u.mutation.ClearDictType()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictTypeI18nUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictTypeI18nUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictTypeI18nUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictTypeI18nUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictTypeI18nUpdate) check() error {
	if v, ok := _u.mutation.TypeName(); ok {
		if err := dicttypei18n.TypeNameValidator(v); err != nil {
			return &ValidationError{Name: "type_name", err: fmt.Errorf(`ent: validator failed for field "DictTypeI18n.type_name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DictTypeI18nUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DictTypeI18nUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DictTypeI18nUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dicttypei18n.Table, dicttypei18n.Columns, sqlgraph.NewFieldSpec(dicttypei18n.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(dicttypei18n.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dicttypei18n.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(dicttypei18n.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dicttypei18n.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dicttypei18n.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(dicttypei18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(dicttypei18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(dicttypei18n.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(dicttypei18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(dicttypei18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(dicttypei18n.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(dicttypei18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(dicttypei18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(dicttypei18n.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dicttypei18n.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(dicttypei18n.FieldDescription, field.TypeString)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(dicttypei18n.FieldTenantID, field.TypeUint32)
	}
	if _u.mutation.LanguageCodeCleared() {
		_spec.ClearField(dicttypei18n.FieldLanguageCode, field.TypeString)
	}
	if value, ok := _u.mutation.TypeName(); ok {
		_spec.SetField(dicttypei18n.FieldTypeName, field.TypeString, value)
	}
	if _u.mutation.TypeNameCleared() {
		_spec.ClearField(dicttypei18n.FieldTypeName, field.TypeString)
	}
	if _u.mutation.DictTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dicttypei18n.DictTypeTable,
			Columns: []string{dicttypei18n.DictTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DictTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dicttypei18n.DictTypeTable,
			Columns: []string{dicttypei18n.DictTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dicttypei18n.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictTypeI18nUpdateOne is the builder for updating a single DictTypeI18n entity.
type DictTypeI18nUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DictTypeI18nMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictTypeI18nUpdateOne) SetUpdatedAt(v time.Time) *DictTypeI18nUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DictTypeI18nUpdateOne) SetNillableUpdatedAt(v *time.Time) *DictTypeI18nUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DictTypeI18nUpdateOne) ClearUpdatedAt() *DictTypeI18nUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictTypeI18nUpdateOne) SetDeletedAt(v time.Time) *DictTypeI18nUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictTypeI18nUpdateOne) SetNillableDeletedAt(v *time.Time) *DictTypeI18nUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictTypeI18nUpdateOne) ClearDeletedAt() *DictTypeI18nUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DictTypeI18nUpdateOne) SetCreatedBy(v uint32) *DictTypeI18nUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DictTypeI18nUpdateOne) SetNillableCreatedBy(v *uint32) *DictTypeI18nUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DictTypeI18nUpdateOne) AddCreatedBy(v int32) *DictTypeI18nUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DictTypeI18nUpdateOne) ClearCreatedBy() *DictTypeI18nUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *DictTypeI18nUpdateOne) SetUpdatedBy(v uint32) *DictTypeI18nUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *DictTypeI18nUpdateOne) SetNillableUpdatedBy(v *uint32) *DictTypeI18nUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *DictTypeI18nUpdateOne) AddUpdatedBy(v int32) *DictTypeI18nUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *DictTypeI18nUpdateOne) ClearUpdatedBy() *DictTypeI18nUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *DictTypeI18nUpdateOne) SetDeletedBy(v uint32) *DictTypeI18nUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *DictTypeI18nUpdateOne) SetNillableDeletedBy(v *uint32) *DictTypeI18nUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *DictTypeI18nUpdateOne) AddDeletedBy(v int32) *DictTypeI18nUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *DictTypeI18nUpdateOne) ClearDeletedBy() *DictTypeI18nUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DictTypeI18nUpdateOne) SetDescription(v string) *DictTypeI18nUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DictTypeI18nUpdateOne) SetNillableDescription(v *string) *DictTypeI18nUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DictTypeI18nUpdateOne) ClearDescription() *DictTypeI18nUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTypeName sets the "type_name" field.
func (_u *DictTypeI18nUpdateOne) SetTypeName(v string) *DictTypeI18nUpdateOne {
	_u.mutation.SetTypeName(v)
	return _u
}

// SetNillableTypeName sets the "type_name" field if the given value is not nil.
func (_u *DictTypeI18nUpdateOne) SetNillableTypeName(v *string) *DictTypeI18nUpdateOne {
	if v != nil {
		_u.SetTypeName(*v)
	}
	return _u
}

// ClearTypeName clears the value of the "type_name" field.
func (_u *DictTypeI18nUpdateOne) ClearTypeName() *DictTypeI18nUpdateOne {
	_u.mutation.ClearTypeName()
	return _u
}

// SetDictTypeID sets the "dict_type" edge to the DictType entity by ID.
func (_u *DictTypeI18nUpdateOne) SetDictTypeID(id uint32) *DictTypeI18nUpdateOne {
	_u.mutation.SetDictTypeID(id)
	return _u
}

// SetNillableDictTypeID sets the "dict_type" edge to the DictType entity by ID if the given value is not nil.
func (_u *DictTypeI18nUpdateOne) SetNillableDictTypeID(id *uint32) *DictTypeI18nUpdateOne {
	if id != nil {
		_u = _u.SetDictTypeID(*id)
	}
	return _u
}

// SetDictType sets the "dict_type" edge to the DictType entity.
func (_u *DictTypeI18nUpdateOne) SetDictType(v *DictType) *DictTypeI18nUpdateOne {
	return _u.SetDictTypeID(v.ID)
}

// Mutation returns the DictTypeI18nMutation object of the builder.
func (_u *DictTypeI18nUpdateOne) Mutation() *DictTypeI18nMutation {
	return _u.mutation
}

// ClearDictType clears the "dict_type" edge to the DictType entity.
func (_u *DictTypeI18nUpdateOne) ClearDictType() *DictTypeI18nUpdateOne {
	_u.mutation.ClearDictType()
	return _u
}

// Where appends a list predicates to the DictTypeI18nUpdate builder.
func (_u *DictTypeI18nUpdateOne) Where(ps ...predicate.DictTypeI18n) *DictTypeI18nUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictTypeI18nUpdateOne) Select(field string, fields ...string) *DictTypeI18nUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DictTypeI18n entity.
func (_u *DictTypeI18nUpdateOne) Save(ctx context.Context) (*DictTypeI18n, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictTypeI18nUpdateOne) SaveX(ctx context.Context) *DictTypeI18n {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictTypeI18nUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictTypeI18nUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictTypeI18nUpdateOne) check() error {
	if v, ok := _u.mutation.TypeName(); ok {
		if err := dicttypei18n.TypeNameValidator(v); err != nil {
			return &ValidationError{Name: "type_name", err: fmt.Errorf(`ent: validator failed for field "DictTypeI18n.type_name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DictTypeI18nUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DictTypeI18nUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DictTypeI18nUpdateOne) sqlSave(ctx context.Context) (_node *DictTypeI18n, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dicttypei18n.Table, dicttypei18n.Columns, sqlgraph.NewFieldSpec(dicttypei18n.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DictTypeI18n.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dicttypei18n.FieldID)
		for _, f := range fields {
			if !dicttypei18n.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dicttypei18n.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(dicttypei18n.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dicttypei18n.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(dicttypei18n.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dicttypei18n.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dicttypei18n.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(dicttypei18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(dicttypei18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(dicttypei18n.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(dicttypei18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(dicttypei18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(dicttypei18n.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(dicttypei18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(dicttypei18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(dicttypei18n.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dicttypei18n.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(dicttypei18n.FieldDescription, field.TypeString)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(dicttypei18n.FieldTenantID, field.TypeUint32)
	}
	if _u.mutation.LanguageCodeCleared() {
		_spec.ClearField(dicttypei18n.FieldLanguageCode, field.TypeString)
	}
	if value, ok := _u.mutation.TypeName(); ok {
		_spec.SetField(dicttypei18n.FieldTypeName, field.TypeString, value)
	}
	if _u.mutation.TypeNameCleared() {
		_spec.ClearField(dicttypei18n.FieldTypeName, field.TypeString)
	}
	if _u.mutation.DictTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dicttypei18n.DictTypeTable,
			Columns: []string{dicttypei18n.DictTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DictTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dicttypei18n.DictTypeTable,
			Columns: []string{dicttypei18n.DictTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DictTypeI18n{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dicttypei18n.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
