// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-uba/app/core/service/internal/data/ent/dicttype"
	"go-wind-uba/app/core/service/internal/data/ent/dicttypei18n"
	"go-wind-uba/app/core/service/internal/data/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictTypeI18nQuery is the builder for querying DictTypeI18n entities.
type DictTypeI18nQuery struct {
	config
	ctx          *QueryContext
	order        []dicttypei18n.OrderOption
	inters       []Interceptor
	predicates   []predicate.DictTypeI18n
	withDictType *DictTypeQuery
	withFKs      bool
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DictTypeI18nQuery builder.
func (_q *DictTypeI18nQuery) Where(ps ...predicate.DictTypeI18n) *DictTypeI18nQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DictTypeI18nQuery) Limit(limit int) *DictTypeI18nQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DictTypeI18nQuery) Offset(offset int) *DictTypeI18nQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DictTypeI18nQuery) Unique(unique bool) *DictTypeI18nQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DictTypeI18nQuery) Order(o ...dicttypei18n.OrderOption) *DictTypeI18nQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDictType chains the current query on the "dict_type" edge.
func (_q *DictTypeI18nQuery) QueryDictType() *DictTypeQuery {
	query := (&DictTypeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dicttypei18n.Table, dicttypei18n.FieldID, selector),
			sqlgraph.To(dicttype.Table, dicttype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dicttypei18n.DictTypeTable, dicttypei18n.DictTypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DictTypeI18n entity from the query.
// Returns a *NotFoundError when no DictTypeI18n was found.
func (_q *DictTypeI18nQuery) First(ctx context.Context) (*DictTypeI18n, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dicttypei18n.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DictTypeI18nQuery) FirstX(ctx context.Context) *DictTypeI18n {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DictTypeI18n ID from the query.
// Returns a *NotFoundError when no DictTypeI18n ID was found.
func (_q *DictTypeI18nQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dicttypei18n.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DictTypeI18nQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DictTypeI18n entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DictTypeI18n entity is found.
// Returns a *NotFoundError when no DictTypeI18n entities are found.
func (_q *DictTypeI18nQuery) Only(ctx context.Context) (*DictTypeI18n, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dicttypei18n.Label}
	default:
		return nil, &NotSingularError{dicttypei18n.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DictTypeI18nQuery) OnlyX(ctx context.Context) *DictTypeI18n {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DictTypeI18n ID in the query.
// Returns a *NotSingularError when more than one DictTypeI18n ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DictTypeI18nQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dicttypei18n.Label}
	default:
		err = &NotSingularError{dicttypei18n.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DictTypeI18nQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DictTypeI18ns.
func (_q *DictTypeI18nQuery) All(ctx context.Context) ([]*DictTypeI18n, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DictTypeI18n, *DictTypeI18nQuery]()
	return withInterceptors[[]*DictTypeI18n](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DictTypeI18nQuery) AllX(ctx context.Context) []*DictTypeI18n {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DictTypeI18n IDs.
func (_q *DictTypeI18nQuery) IDs(ctx context.Context) (ids []uint32, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(dicttypei18n.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DictTypeI18nQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DictTypeI18nQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DictTypeI18nQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DictTypeI18nQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DictTypeI18nQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DictTypeI18nQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DictTypeI18nQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DictTypeI18nQuery) Clone() *DictTypeI18nQuery {
	if _q == nil {
		return nil
	}
	return &DictTypeI18nQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]dicttypei18n.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.DictTypeI18n{}, _q.predicates...),
		withDictType: _q.withDictType.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithDictType tells the query-builder to eager-load the nodes that are connected to
// the "dict_type" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DictTypeI18nQuery) WithDictType(opts ...func(*DictTypeQuery)) *DictTypeI18nQuery {
	query := (&DictTypeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDictType = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DictTypeI18n.Query().
//		GroupBy(dicttypei18n.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DictTypeI18nQuery) GroupBy(field string, fields ...string) *DictTypeI18nGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DictTypeI18nGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = dicttypei18n.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.DictTypeI18n.Query().
//		Select(dicttypei18n.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *DictTypeI18nQuery) Select(fields ...string) *DictTypeI18nSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DictTypeI18nSelect{DictTypeI18nQuery: _q}
	sbuild.label = dicttypei18n.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DictTypeI18nSelect configured with the given aggregations.
func (_q *DictTypeI18nQuery) Aggregate(fns ...AggregateFunc) *DictTypeI18nSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DictTypeI18nQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !dicttypei18n.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if dicttypei18n.Policy == nil {
		return errors.New("ent: uninitialized dicttypei18n.Policy (forgotten import ent/runtime?)")
	}
	if err := dicttypei18n.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *DictTypeI18nQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DictTypeI18n, error) {
	var (
		nodes       = []*DictTypeI18n{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withDictType != nil,
		}
	)
	if _q.withDictType != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, dicttypei18n.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DictTypeI18n).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DictTypeI18n{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDictType; query != nil {
		if err := _q.loadDictType(ctx, query, nodes, nil,
			func(n *DictTypeI18n, e *DictType) { n.Edges.DictType = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DictTypeI18nQuery) loadDictType(ctx context.Context, query *DictTypeQuery, nodes []*DictTypeI18n, init func(*DictTypeI18n), assign func(*DictTypeI18n, *DictType)) error {
	ids := make([]uint32, 0, len(nodes))
	nodeids := make(map[uint32][]*DictTypeI18n)
	for i := range nodes {
		if nodes[i].type_id == nil {
			continue
		}
		fk := *nodes[i].type_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(dicttype.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "type_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DictTypeI18nQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DictTypeI18nQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dicttypei18n.Table, dicttypei18n.Columns, sqlgraph.NewFieldSpec(dicttypei18n.FieldID, field.TypeUint32))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dicttypei18n.FieldID)
		for i := range fields {
			if fields[i] != dicttypei18n.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DictTypeI18nQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(dicttypei18n.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = dicttypei18n.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *DictTypeI18nQuery) ForUpdate(opts ...sql.LockOption) *DictTypeI18nQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *DictTypeI18nQuery) ForShare(opts ...sql.LockOption) *DictTypeI18nQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *DictTypeI18nQuery) Modify(modifiers ...func(s *sql.Selector)) *DictTypeI18nSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// DictTypeI18nGroupBy is the group-by builder for DictTypeI18n entities.
type DictTypeI18nGroupBy struct {
	selector
	build *DictTypeI18nQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DictTypeI18nGroupBy) Aggregate(fns ...AggregateFunc) *DictTypeI18nGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DictTypeI18nGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DictTypeI18nQuery, *DictTypeI18nGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DictTypeI18nGroupBy) sqlScan(ctx context.Context, root *DictTypeI18nQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DictTypeI18nSelect is the builder for selecting fields of DictTypeI18n entities.
type DictTypeI18nSelect struct {
	*DictTypeI18nQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DictTypeI18nSelect) Aggregate(fns ...AggregateFunc) *DictTypeI18nSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DictTypeI18nSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DictTypeI18nQuery, *DictTypeI18nSelect](ctx, _s.DictTypeI18nQuery, _s, _s.inters, v)
}

func (_s *DictTypeI18nSelect) sqlScan(ctx context.Context, root *DictTypeI18nQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *DictTypeI18nSelect) Modify(modifiers ...func(s *sql.Selector)) *DictTypeI18nSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
