// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-uba/app/core/service/internal/data/ent/idmapping"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IDMappingCreate is the builder for creating a IDMapping entity.
type IDMappingCreate struct {
	config
	mutation *IDMappingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *IDMappingCreate) SetTenantID(v uint32) *IDMappingCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *IDMappingCreate) SetNillableTenantID(v *uint32) *IDMappingCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IDMappingCreate) SetCreatedAt(v time.Time) *IDMappingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IDMappingCreate) SetNillableCreatedAt(v *time.Time) *IDMappingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IDMappingCreate) SetUpdatedAt(v time.Time) *IDMappingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IDMappingCreate) SetNillableUpdatedAt(v *time.Time) *IDMappingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *IDMappingCreate) SetDeletedAt(v time.Time) *IDMappingCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *IDMappingCreate) SetNillableDeletedAt(v *time.Time) *IDMappingCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetGlobalUserID sets the "global_user_id" field.
func (_c *IDMappingCreate) SetGlobalUserID(v string) *IDMappingCreate {
	_c.mutation.SetGlobalUserID(v)
	return _c
}

// SetIDType sets the "id_type" field.
func (_c *IDMappingCreate) SetIDType(v string) *IDMappingCreate {
	_c.mutation.SetIDType(v)
	return _c
}

// SetIDValue sets the "id_value" field.
func (_c *IDMappingCreate) SetIDValue(v string) *IDMappingCreate {
	_c.mutation.SetIDValue(v)
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *IDMappingCreate) SetConfidence(v float64) *IDMappingCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *IDMappingCreate) SetNillableConfidence(v *float64) *IDMappingCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetLinkSource sets the "link_source" field.
func (_c *IDMappingCreate) SetLinkSource(v string) *IDMappingCreate {
	_c.mutation.SetLinkSource(v)
	return _c
}

// SetNillableLinkSource sets the "link_source" field if the given value is not nil.
func (_c *IDMappingCreate) SetNillableLinkSource(v *string) *IDMappingCreate {
	if v != nil {
		_c.SetLinkSource(*v)
	}
	return _c
}

// SetFirstSeen sets the "first_seen" field.
func (_c *IDMappingCreate) SetFirstSeen(v time.Time) *IDMappingCreate {
	_c.mutation.SetFirstSeen(v)
	return _c
}

// SetNillableFirstSeen sets the "first_seen" field if the given value is not nil.
func (_c *IDMappingCreate) SetNillableFirstSeen(v *time.Time) *IDMappingCreate {
	if v != nil {
		_c.SetFirstSeen(*v)
	}
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *IDMappingCreate) SetLastSeen(v time.Time) *IDMappingCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_c *IDMappingCreate) SetNillableLastSeen(v *time.Time) *IDMappingCreate {
	if v != nil {
		_c.SetLastSeen(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *IDMappingCreate) SetIsActive(v bool) *IDMappingCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *IDMappingCreate) SetNillableIsActive(v *bool) *IDMappingCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IDMappingCreate) SetID(v uint32) *IDMappingCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the IDMappingMutation object of the builder.
func (_c *IDMappingCreate) Mutation() *IDMappingMutation {
	return _c.mutation
}

// Save creates the IDMapping in the database.
func (_c *IDMappingCreate) Save(ctx context.Context) (*IDMapping, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IDMappingCreate) SaveX(ctx context.Context) *IDMapping {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IDMappingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IDMappingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IDMappingCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := idmapping.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		v := idmapping.DefaultConfidence
		_c.mutation.SetConfidence(v)
	}
	if _, ok := _c.mutation.LinkSource(); !ok {
		v := idmapping.DefaultLinkSource
		_c.mutation.SetLinkSource(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := idmapping.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *IDMappingCreate) check() error {
	if _, ok := _c.mutation.GlobalUserID(); !ok {
		return &ValidationError{Name: "global_user_id", err: errors.New(`ent: missing required field "IDMapping.global_user_id"`)}
	}
	if v, ok := _c.mutation.GlobalUserID(); ok {
		if err := idmapping.GlobalUserIDValidator(v); err != nil {
			return &ValidationError{Name: "global_user_id", err: fmt.Errorf(`ent: validator failed for field "IDMapping.global_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IDType(); !ok {
		return &ValidationError{Name: "id_type", err: errors.New(`ent: missing required field "IDMapping.id_type"`)}
	}
	if v, ok := _c.mutation.IDType(); ok {
		if err := idmapping.IDTypeValidator(v); err != nil {
			return &ValidationError{Name: "id_type", err: fmt.Errorf(`ent: validator failed for field "IDMapping.id_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IDValue(); !ok {
		return &ValidationError{Name: "id_value", err: errors.New(`ent: missing required field "IDMapping.id_value"`)}
	}
	if v, ok := _c.mutation.IDValue(); ok {
		if err := idmapping.IDValueValidator(v); err != nil {
			return &ValidationError{Name: "id_value", err: fmt.Errorf(`ent: validator failed for field "IDMapping.id_value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "IDMapping.confidence"`)}
	}
	if _, ok := _c.mutation.LinkSource(); !ok {
		return &ValidationError{Name: "link_source", err: errors.New(`ent: missing required field "IDMapping.link_source"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "IDMapping.is_active"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := idmapping.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "IDMapping.id": %w`, err)}
		}
	}
	return nil
}

func (_c *IDMappingCreate) sqlSave(ctx context.Context) (*IDMapping, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IDMappingCreate) createSpec() (*IDMapping, *sqlgraph.CreateSpec) {
	var (
		_node = &IDMapping{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(idmapping.Table, sqlgraph.NewFieldSpec(idmapping.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(idmapping.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(idmapping.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(idmapping.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(idmapping.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.GlobalUserID(); ok {
		_spec.SetField(idmapping.FieldGlobalUserID, field.TypeString, value)
		_node.GlobalUserID = value
	}
	if value, ok := _c.mutation.IDType(); ok {
		_spec.SetField(idmapping.FieldIDType, field.TypeString, value)
		_node.IDType = value
	}
	if value, ok := _c.mutation.IDValue(); ok {
		_spec.SetField(idmapping.FieldIDValue, field.TypeString, value)
		_node.IDValue = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(idmapping.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.LinkSource(); ok {
		_spec.SetField(idmapping.FieldLinkSource, field.TypeString, value)
		_node.LinkSource = value
	}
	if value, ok := _c.mutation.FirstSeen(); ok {
		_spec.SetField(idmapping.FieldFirstSeen, field.TypeTime, value)
		_node.FirstSeen = &value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(idmapping.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(idmapping.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IDMapping.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IDMappingUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *IDMappingCreate) OnConflict(opts ...sql.ConflictOption) *IDMappingUpsertOne {
	_c.conflict = opts
	return &IDMappingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IDMapping.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IDMappingCreate) OnConflictColumns(columns ...string) *IDMappingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IDMappingUpsertOne{
		create: _c,
	}
}

type (
	// IDMappingUpsertOne is the builder for "upsert"-ing
	//  one IDMapping node.
	IDMappingUpsertOne struct {
		create *IDMappingCreate
	}

	// IDMappingUpsert is the "OnConflict" setter.
	IDMappingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IDMappingUpsert) SetUpdatedAt(v time.Time) *IDMappingUpsert {
	u.Set(idmapping.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IDMappingUpsert) UpdateUpdatedAt() *IDMappingUpsert {
	u.SetExcluded(idmapping.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *IDMappingUpsert) ClearUpdatedAt() *IDMappingUpsert {
	u.SetNull(idmapping.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IDMappingUpsert) SetDeletedAt(v time.Time) *IDMappingUpsert {
	u.Set(idmapping.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IDMappingUpsert) UpdateDeletedAt() *IDMappingUpsert {
	u.SetExcluded(idmapping.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IDMappingUpsert) ClearDeletedAt() *IDMappingUpsert {
	u.SetNull(idmapping.FieldDeletedAt)
	return u
}

// SetGlobalUserID sets the "global_user_id" field.
func (u *IDMappingUpsert) SetGlobalUserID(v string) *IDMappingUpsert {
	u.Set(idmapping.FieldGlobalUserID, v)
	return u
}

// UpdateGlobalUserID sets the "global_user_id" field to the value that was provided on create.
func (u *IDMappingUpsert) UpdateGlobalUserID() *IDMappingUpsert {
	u.SetExcluded(idmapping.FieldGlobalUserID)
	return u
}

// SetIDType sets the "id_type" field.
func (u *IDMappingUpsert) SetIDType(v string) *IDMappingUpsert {
	u.Set(idmapping.FieldIDType, v)
	return u
}

// UpdateIDType sets the "id_type" field to the value that was provided on create.
func (u *IDMappingUpsert) UpdateIDType() *IDMappingUpsert {
	u.SetExcluded(idmapping.FieldIDType)
	return u
}

// SetIDValue sets the "id_value" field.
func (u *IDMappingUpsert) SetIDValue(v string) *IDMappingUpsert {
	u.Set(idmapping.FieldIDValue, v)
	return u
}

// UpdateIDValue sets the "id_value" field to the value that was provided on create.
func (u *IDMappingUpsert) UpdateIDValue() *IDMappingUpsert {
	u.SetExcluded(idmapping.FieldIDValue)
	return u
}

// SetConfidence sets the "confidence" field.
func (u *IDMappingUpsert) SetConfidence(v float64) *IDMappingUpsert {
	u.Set(idmapping.FieldConfidence, v)
	return u
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *IDMappingUpsert) UpdateConfidence() *IDMappingUpsert {
	u.SetExcluded(idmapping.FieldConfidence)
	return u
}

// AddConfidence adds v to the "confidence" field.
func (u *IDMappingUpsert) AddConfidence(v float64) *IDMappingUpsert {
	u.Add(idmapping.FieldConfidence, v)
	return u
}

// SetLinkSource sets the "link_source" field.
func (u *IDMappingUpsert) SetLinkSource(v string) *IDMappingUpsert {
	u.Set(idmapping.FieldLinkSource, v)
	return u
}

// UpdateLinkSource sets the "link_source" field to the value that was provided on create.
func (u *IDMappingUpsert) UpdateLinkSource() *IDMappingUpsert {
	u.SetExcluded(idmapping.FieldLinkSource)
	return u
}

// SetFirstSeen sets the "first_seen" field.
func (u *IDMappingUpsert) SetFirstSeen(v time.Time) *IDMappingUpsert {
	u.Set(idmapping.FieldFirstSeen, v)
	return u
}

// UpdateFirstSeen sets the "first_seen" field to the value that was provided on create.
func (u *IDMappingUpsert) UpdateFirstSeen() *IDMappingUpsert {
	u.SetExcluded(idmapping.FieldFirstSeen)
	return u
}

// ClearFirstSeen clears the value of the "first_seen" field.
func (u *IDMappingUpsert) ClearFirstSeen() *IDMappingUpsert {
	u.SetNull(idmapping.FieldFirstSeen)
	return u
}

// SetLastSeen sets the "last_seen" field.
func (u *IDMappingUpsert) SetLastSeen(v time.Time) *IDMappingUpsert {
	u.Set(idmapping.FieldLastSeen, v)
	return u
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *IDMappingUpsert) UpdateLastSeen() *IDMappingUpsert {
	u.SetExcluded(idmapping.FieldLastSeen)
	return u
}

// ClearLastSeen clears the value of the "last_seen" field.
func (u *IDMappingUpsert) ClearLastSeen() *IDMappingUpsert {
	u.SetNull(idmapping.FieldLastSeen)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *IDMappingUpsert) SetIsActive(v bool) *IDMappingUpsert {
	u.Set(idmapping.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *IDMappingUpsert) UpdateIsActive() *IDMappingUpsert {
	u.SetExcluded(idmapping.FieldIsActive)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.IDMapping.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(idmapping.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IDMappingUpsertOne) UpdateNewValues() *IDMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(idmapping.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(idmapping.FieldTenantID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(idmapping.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IDMapping.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IDMappingUpsertOne) Ignore() *IDMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IDMappingUpsertOne) DoNothing() *IDMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IDMappingCreate.OnConflict
// documentation for more info.
func (u *IDMappingUpsertOne) Update(set func(*IDMappingUpsert)) *IDMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IDMappingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IDMappingUpsertOne) SetUpdatedAt(v time.Time) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IDMappingUpsertOne) UpdateUpdatedAt() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *IDMappingUpsertOne) ClearUpdatedAt() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IDMappingUpsertOne) SetDeletedAt(v time.Time) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IDMappingUpsertOne) UpdateDeletedAt() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IDMappingUpsertOne) ClearDeletedAt() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.ClearDeletedAt()
	})
}

// SetGlobalUserID sets the "global_user_id" field.
func (u *IDMappingUpsertOne) SetGlobalUserID(v string) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetGlobalUserID(v)
	})
}

// UpdateGlobalUserID sets the "global_user_id" field to the value that was provided on create.
func (u *IDMappingUpsertOne) UpdateGlobalUserID() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateGlobalUserID()
	})
}

// SetIDType sets the "id_type" field.
func (u *IDMappingUpsertOne) SetIDType(v string) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetIDType(v)
	})
}

// UpdateIDType sets the "id_type" field to the value that was provided on create.
func (u *IDMappingUpsertOne) UpdateIDType() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateIDType()
	})
}

// SetIDValue sets the "id_value" field.
func (u *IDMappingUpsertOne) SetIDValue(v string) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetIDValue(v)
	})
}

// UpdateIDValue sets the "id_value" field to the value that was provided on create.
func (u *IDMappingUpsertOne) UpdateIDValue() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateIDValue()
	})
}

// SetConfidence sets the "confidence" field.
func (u *IDMappingUpsertOne) SetConfidence(v float64) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *IDMappingUpsertOne) AddConfidence(v float64) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *IDMappingUpsertOne) UpdateConfidence() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateConfidence()
	})
}

// SetLinkSource sets the "link_source" field.
func (u *IDMappingUpsertOne) SetLinkSource(v string) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetLinkSource(v)
	})
}

// UpdateLinkSource sets the "link_source" field to the value that was provided on create.
func (u *IDMappingUpsertOne) UpdateLinkSource() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateLinkSource()
	})
}

// SetFirstSeen sets the "first_seen" field.
func (u *IDMappingUpsertOne) SetFirstSeen(v time.Time) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetFirstSeen(v)
	})
}

// UpdateFirstSeen sets the "first_seen" field to the value that was provided on create.
func (u *IDMappingUpsertOne) UpdateFirstSeen() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateFirstSeen()
	})
}

// ClearFirstSeen clears the value of the "first_seen" field.
func (u *IDMappingUpsertOne) ClearFirstSeen() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.ClearFirstSeen()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *IDMappingUpsertOne) SetLastSeen(v time.Time) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *IDMappingUpsertOne) UpdateLastSeen() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateLastSeen()
	})
}

// ClearLastSeen clears the value of the "last_seen" field.
func (u *IDMappingUpsertOne) ClearLastSeen() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.ClearLastSeen()
	})
}

// SetIsActive sets the "is_active" field.
func (u *IDMappingUpsertOne) SetIsActive(v bool) *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *IDMappingUpsertOne) UpdateIsActive() *IDMappingUpsertOne {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateIsActive()
	})
}

// Exec executes the query.
func (u *IDMappingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IDMappingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IDMappingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IDMappingUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IDMappingUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IDMappingCreateBulk is the builder for creating many IDMapping entities in bulk.
type IDMappingCreateBulk struct {
	config
	err      error
	builders []*IDMappingCreate
	conflict []sql.ConflictOption
}

// Save creates the IDMapping entities in the database.
func (_c *IDMappingCreateBulk) Save(ctx context.Context) ([]*IDMapping, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IDMapping, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IDMappingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IDMappingCreateBulk) SaveX(ctx context.Context) []*IDMapping {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IDMappingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IDMappingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IDMapping.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IDMappingUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *IDMappingCreateBulk) OnConflict(opts ...sql.ConflictOption) *IDMappingUpsertBulk {
	_c.conflict = opts
	return &IDMappingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IDMapping.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IDMappingCreateBulk) OnConflictColumns(columns ...string) *IDMappingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IDMappingUpsertBulk{
		create: _c,
	}
}

// IDMappingUpsertBulk is the builder for "upsert"-ing
// a bulk of IDMapping nodes.
type IDMappingUpsertBulk struct {
	create *IDMappingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IDMapping.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(idmapping.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IDMappingUpsertBulk) UpdateNewValues() *IDMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(idmapping.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(idmapping.FieldTenantID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(idmapping.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IDMapping.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IDMappingUpsertBulk) Ignore() *IDMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IDMappingUpsertBulk) DoNothing() *IDMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IDMappingCreateBulk.OnConflict
// documentation for more info.
func (u *IDMappingUpsertBulk) Update(set func(*IDMappingUpsert)) *IDMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IDMappingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IDMappingUpsertBulk) SetUpdatedAt(v time.Time) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IDMappingUpsertBulk) UpdateUpdatedAt() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *IDMappingUpsertBulk) ClearUpdatedAt() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IDMappingUpsertBulk) SetDeletedAt(v time.Time) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IDMappingUpsertBulk) UpdateDeletedAt() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IDMappingUpsertBulk) ClearDeletedAt() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.ClearDeletedAt()
	})
}

// SetGlobalUserID sets the "global_user_id" field.
func (u *IDMappingUpsertBulk) SetGlobalUserID(v string) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetGlobalUserID(v)
	})
}

// UpdateGlobalUserID sets the "global_user_id" field to the value that was provided on create.
func (u *IDMappingUpsertBulk) UpdateGlobalUserID() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateGlobalUserID()
	})
}

// SetIDType sets the "id_type" field.
func (u *IDMappingUpsertBulk) SetIDType(v string) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetIDType(v)
	})
}

// UpdateIDType sets the "id_type" field to the value that was provided on create.
func (u *IDMappingUpsertBulk) UpdateIDType() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateIDType()
	})
}

// SetIDValue sets the "id_value" field.
func (u *IDMappingUpsertBulk) SetIDValue(v string) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetIDValue(v)
	})
}

// UpdateIDValue sets the "id_value" field to the value that was provided on create.
func (u *IDMappingUpsertBulk) UpdateIDValue() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateIDValue()
	})
}

// SetConfidence sets the "confidence" field.
func (u *IDMappingUpsertBulk) SetConfidence(v float64) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *IDMappingUpsertBulk) AddConfidence(v float64) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *IDMappingUpsertBulk) UpdateConfidence() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateConfidence()
	})
}

// SetLinkSource sets the "link_source" field.
func (u *IDMappingUpsertBulk) SetLinkSource(v string) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetLinkSource(v)
	})
}

// UpdateLinkSource sets the "link_source" field to the value that was provided on create.
func (u *IDMappingUpsertBulk) UpdateLinkSource() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateLinkSource()
	})
}

// SetFirstSeen sets the "first_seen" field.
func (u *IDMappingUpsertBulk) SetFirstSeen(v time.Time) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetFirstSeen(v)
	})
}

// UpdateFirstSeen sets the "first_seen" field to the value that was provided on create.
func (u *IDMappingUpsertBulk) UpdateFirstSeen() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateFirstSeen()
	})
}

// ClearFirstSeen clears the value of the "first_seen" field.
func (u *IDMappingUpsertBulk) ClearFirstSeen() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.ClearFirstSeen()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *IDMappingUpsertBulk) SetLastSeen(v time.Time) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *IDMappingUpsertBulk) UpdateLastSeen() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateLastSeen()
	})
}

// ClearLastSeen clears the value of the "last_seen" field.
func (u *IDMappingUpsertBulk) ClearLastSeen() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.ClearLastSeen()
	})
}

// SetIsActive sets the "is_active" field.
func (u *IDMappingUpsertBulk) SetIsActive(v bool) *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *IDMappingUpsertBulk) UpdateIsActive() *IDMappingUpsertBulk {
	return u.Update(func(s *IDMappingUpsert) {
		s.UpdateIsActive()
	})
}

// Exec executes the query.
func (u *IDMappingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IDMappingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IDMappingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IDMappingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
