// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	ubapb "go-wind-uba/api/gen/go/uba/service/v1"
	"go-wind-uba/app/core/service/internal/data/ent/predicate"
	"go-wind-uba/app/core/service/internal/data/ent/riskrule"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// RiskRuleUpdate is the builder for updating RiskRule entities.
type RiskRuleUpdate struct {
	config
	hooks     []Hook
	mutation  *RiskRuleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RiskRuleUpdate builder.
func (_u *RiskRuleUpdate) Where(ps ...predicate.RiskRule) *RiskRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RiskRuleUpdate) SetUpdatedAt(v time.Time) *RiskRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableUpdatedAt(v *time.Time) *RiskRuleUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *RiskRuleUpdate) ClearUpdatedAt() *RiskRuleUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RiskRuleUpdate) SetDeletedAt(v time.Time) *RiskRuleUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableDeletedAt(v *time.Time) *RiskRuleUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RiskRuleUpdate) ClearDeletedAt() *RiskRuleUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RiskRuleUpdate) SetCreatedBy(v uint32) *RiskRuleUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableCreatedBy(v *uint32) *RiskRuleUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *RiskRuleUpdate) AddCreatedBy(v int32) *RiskRuleUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *RiskRuleUpdate) ClearCreatedBy() *RiskRuleUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *RiskRuleUpdate) SetUpdatedBy(v uint32) *RiskRuleUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableUpdatedBy(v *uint32) *RiskRuleUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *RiskRuleUpdate) AddUpdatedBy(v int32) *RiskRuleUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *RiskRuleUpdate) ClearUpdatedBy() *RiskRuleUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *RiskRuleUpdate) SetDeletedBy(v uint32) *RiskRuleUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableDeletedBy(v *uint32) *RiskRuleUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *RiskRuleUpdate) AddDeletedBy(v int32) *RiskRuleUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *RiskRuleUpdate) ClearDeletedBy() *RiskRuleUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *RiskRuleUpdate) SetName(v string) *RiskRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableName(v *string) *RiskRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *RiskRuleUpdate) ClearName() *RiskRuleUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *RiskRuleUpdate) SetDescription(v string) *RiskRuleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableDescription(v *string) *RiskRuleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RiskRuleUpdate) ClearDescription() *RiskRuleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetRiskType sets the "risk_type" field.
func (_u *RiskRuleUpdate) SetRiskType(v riskrule.RiskType) *RiskRuleUpdate {
	_u.mutation.SetRiskType(v)
	return _u
}

// SetNillableRiskType sets the "risk_type" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableRiskType(v *riskrule.RiskType) *RiskRuleUpdate {
	if v != nil {
		_u.SetRiskType(*v)
	}
	return _u
}

// ClearRiskType clears the value of the "risk_type" field.
func (_u *RiskRuleUpdate) ClearRiskType() *RiskRuleUpdate {
	_u.mutation.ClearRiskType()
	return _u
}

// SetDefaultLevel sets the "default_level" field.
func (_u *RiskRuleUpdate) SetDefaultLevel(v riskrule.DefaultLevel) *RiskRuleUpdate {
	_u.mutation.SetDefaultLevel(v)
	return _u
}

// SetNillableDefaultLevel sets the "default_level" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableDefaultLevel(v *riskrule.DefaultLevel) *RiskRuleUpdate {
	if v != nil {
		_u.SetDefaultLevel(*v)
	}
	return _u
}

// ClearDefaultLevel clears the value of the "default_level" field.
func (_u *RiskRuleUpdate) ClearDefaultLevel() *RiskRuleUpdate {
	_u.mutation.ClearDefaultLevel()
	return _u
}

// SetCondition sets the "condition" field.
func (_u *RiskRuleUpdate) SetCondition(v map[string]interface{}) *RiskRuleUpdate {
	_u.mutation.SetCondition(v)
	return _u
}

// ClearCondition clears the value of the "condition" field.
func (_u *RiskRuleUpdate) ClearCondition() *RiskRuleUpdate {
	_u.mutation.ClearCondition()
	return _u
}

// SetActions sets the "actions" field.
func (_u *RiskRuleUpdate) SetActions(v []*ubapb.RiskAction) *RiskRuleUpdate {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *RiskRuleUpdate) AppendActions(v []*ubapb.RiskAction) *RiskRuleUpdate {
	_u.mutation.AppendActions(v)
	return _u
}

// ClearActions clears the value of the "actions" field.
func (_u *RiskRuleUpdate) ClearActions() *RiskRuleUpdate {
	_u.mutation.ClearActions()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RiskRuleUpdate) SetEnabled(v bool) *RiskRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableEnabled(v *bool) *RiskRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// ClearEnabled clears the value of the "enabled" field.
func (_u *RiskRuleUpdate) ClearEnabled() *RiskRuleUpdate {
	_u.mutation.ClearEnabled()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *RiskRuleUpdate) SetPriority(v uint32) *RiskRuleUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillablePriority(v *uint32) *RiskRuleUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *RiskRuleUpdate) AddPriority(v int32) *RiskRuleUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// ClearPriority clears the value of the "priority" field.
func (_u *RiskRuleUpdate) ClearPriority() *RiskRuleUpdate {
	_u.mutation.ClearPriority()
	return _u
}

// SetCode sets the "code" field.
func (_u *RiskRuleUpdate) SetCode(v string) *RiskRuleUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableCode(v *string) *RiskRuleUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *RiskRuleUpdate) ClearCode() *RiskRuleUpdate {
	_u.mutation.ClearCode()
	return _u
}

// SetRuleExpression sets the "rule_expression" field.
func (_u *RiskRuleUpdate) SetRuleExpression(v string) *RiskRuleUpdate {
	_u.mutation.SetRuleExpression(v)
	return _u
}

// SetNillableRuleExpression sets the "rule_expression" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableRuleExpression(v *string) *RiskRuleUpdate {
	if v != nil {
		_u.SetRuleExpression(*v)
	}
	return _u
}

// ClearRuleExpression clears the value of the "rule_expression" field.
func (_u *RiskRuleUpdate) ClearRuleExpression() *RiskRuleUpdate {
	_u.mutation.ClearRuleExpression()
	return _u
}

// SetRuleConfig sets the "rule_config" field.
func (_u *RiskRuleUpdate) SetRuleConfig(v map[string]interface{}) *RiskRuleUpdate {
	_u.mutation.SetRuleConfig(v)
	return _u
}

// ClearRuleConfig clears the value of the "rule_config" field.
func (_u *RiskRuleUpdate) ClearRuleConfig() *RiskRuleUpdate {
	_u.mutation.ClearRuleConfig()
	return _u
}

// SetExecMode sets the "exec_mode" field.
func (_u *RiskRuleUpdate) SetExecMode(v riskrule.ExecMode) *RiskRuleUpdate {
	_u.mutation.SetExecMode(v)
	return _u
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableExecMode(v *riskrule.ExecMode) *RiskRuleUpdate {
	if v != nil {
		_u.SetExecMode(*v)
	}
	return _u
}

// ClearExecMode clears the value of the "exec_mode" field.
func (_u *RiskRuleUpdate) ClearExecMode() *RiskRuleUpdate {
	_u.mutation.ClearExecMode()
	return _u
}

// SetTriggerCount sets the "trigger_count" field.
func (_u *RiskRuleUpdate) SetTriggerCount(v uint64) *RiskRuleUpdate {
	_u.mutation.ResetTriggerCount()
	_u.mutation.SetTriggerCount(v)
	return _u
}

// SetNillableTriggerCount sets the "trigger_count" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableTriggerCount(v *uint64) *RiskRuleUpdate {
	if v != nil {
		_u.SetTriggerCount(*v)
	}
	return _u
}

// AddTriggerCount adds value to the "trigger_count" field.
func (_u *RiskRuleUpdate) AddTriggerCount(v int64) *RiskRuleUpdate {
	_u.mutation.AddTriggerCount(v)
	return _u
}

// ClearTriggerCount clears the value of the "trigger_count" field.
func (_u *RiskRuleUpdate) ClearTriggerCount() *RiskRuleUpdate {
	_u.mutation.ClearTriggerCount()
	return _u
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_u *RiskRuleUpdate) SetLastTriggeredAt(v time.Time) *RiskRuleUpdate {
	_u.mutation.SetLastTriggeredAt(v)
	return _u
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_u *RiskRuleUpdate) SetNillableLastTriggeredAt(v *time.Time) *RiskRuleUpdate {
	if v != nil {
		_u.SetLastTriggeredAt(*v)
	}
	return _u
}

// ClearLastTriggeredAt clears the value of the "last_triggered_at" field.
func (_u *RiskRuleUpdate) ClearLastTriggeredAt() *RiskRuleUpdate {
	_u.mutation.ClearLastTriggeredAt()
	return _u
}

// Mutation returns the RiskRuleMutation object of the builder.
func (_u *RiskRuleUpdate) Mutation() *RiskRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RiskRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RiskRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RiskRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RiskRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RiskRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := riskrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RiskRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RiskType(); ok {
		if err := riskrule.RiskTypeValidator(v); err != nil {
			return &ValidationError{Name: "risk_type", err: fmt.Errorf(`ent: validator failed for field "RiskRule.risk_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultLevel(); ok {
		if err := riskrule.DefaultLevelValidator(v); err != nil {
			return &ValidationError{Name: "default_level", err: fmt.Errorf(`ent: validator failed for field "RiskRule.default_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := riskrule.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RiskRule.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecMode(); ok {
		if err := riskrule.ExecModeValidator(v); err != nil {
			return &ValidationError{Name: "exec_mode", err: fmt.Errorf(`ent: validator failed for field "RiskRule.exec_mode": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RiskRuleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RiskRuleUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RiskRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(riskrule.Table, riskrule.Columns, sqlgraph.NewFieldSpec(riskrule.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(riskrule.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(riskrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(riskrule.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(riskrule.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(riskrule.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(riskrule.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(riskrule.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(riskrule.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(riskrule.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(riskrule.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(riskrule.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(riskrule.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(riskrule.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(riskrule.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(riskrule.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(riskrule.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(riskrule.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(riskrule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(riskrule.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.RiskType(); ok {
		_spec.SetField(riskrule.FieldRiskType, field.TypeEnum, value)
	}
	if _u.mutation.RiskTypeCleared() {
		_spec.ClearField(riskrule.FieldRiskType, field.TypeEnum)
	}
	if value, ok := _u.mutation.DefaultLevel(); ok {
		_spec.SetField(riskrule.FieldDefaultLevel, field.TypeEnum, value)
	}
	if _u.mutation.DefaultLevelCleared() {
		_spec.ClearField(riskrule.FieldDefaultLevel, field.TypeEnum)
	}
	if value, ok := _u.mutation.Condition(); ok {
		_spec.SetField(riskrule.FieldCondition, field.TypeJSON, value)
	}
	if _u.mutation.ConditionCleared() {
		_spec.ClearField(riskrule.FieldCondition, field.TypeJSON)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(riskrule.FieldActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, riskrule.FieldActions, value)
		})
	}
	if _u.mutation.ActionsCleared() {
		_spec.ClearField(riskrule.FieldActions, field.TypeJSON)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(riskrule.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.EnabledCleared() {
		_spec.ClearField(riskrule.FieldEnabled, field.TypeBool)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(riskrule.FieldPriority, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(riskrule.FieldPriority, field.TypeUint32, value)
	}
	if _u.mutation.PriorityCleared() {
		_spec.ClearField(riskrule.FieldPriority, field.TypeUint32)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(riskrule.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(riskrule.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.RuleExpression(); ok {
		_spec.SetField(riskrule.FieldRuleExpression, field.TypeString, value)
	}
	if _u.mutation.RuleExpressionCleared() {
		_spec.ClearField(riskrule.FieldRuleExpression, field.TypeString)
	}
	if value, ok := _u.mutation.RuleConfig(); ok {
		_spec.SetField(riskrule.FieldRuleConfig, field.TypeJSON, value)
	}
	if _u.mutation.RuleConfigCleared() {
		_spec.ClearField(riskrule.FieldRuleConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExecMode(); ok {
		_spec.SetField(riskrule.FieldExecMode, field.TypeEnum, value)
	}
	if _u.mutation.ExecModeCleared() {
		_spec.ClearField(riskrule.FieldExecMode, field.TypeEnum)
	}
	if value, ok := _u.mutation.TriggerCount(); ok {
		_spec.SetField(riskrule.FieldTriggerCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTriggerCount(); ok {
		_spec.AddField(riskrule.FieldTriggerCount, field.TypeUint64, value)
	}
	if _u.mutation.TriggerCountCleared() {
		_spec.ClearField(riskrule.FieldTriggerCount, field.TypeUint64)
	}
	if value, ok := _u.mutation.LastTriggeredAt(); ok {
		_spec.SetField(riskrule.FieldLastTriggeredAt, field.TypeTime, value)
	}
	if _u.mutation.LastTriggeredAtCleared() {
		_spec.ClearField(riskrule.FieldLastTriggeredAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{riskrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RiskRuleUpdateOne is the builder for updating a single RiskRule entity.
type RiskRuleUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RiskRuleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RiskRuleUpdateOne) SetUpdatedAt(v time.Time) *RiskRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableUpdatedAt(v *time.Time) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *RiskRuleUpdateOne) ClearUpdatedAt() *RiskRuleUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RiskRuleUpdateOne) SetDeletedAt(v time.Time) *RiskRuleUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableDeletedAt(v *time.Time) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RiskRuleUpdateOne) ClearDeletedAt() *RiskRuleUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RiskRuleUpdateOne) SetCreatedBy(v uint32) *RiskRuleUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableCreatedBy(v *uint32) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *RiskRuleUpdateOne) AddCreatedBy(v int32) *RiskRuleUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *RiskRuleUpdateOne) ClearCreatedBy() *RiskRuleUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *RiskRuleUpdateOne) SetUpdatedBy(v uint32) *RiskRuleUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableUpdatedBy(v *uint32) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *RiskRuleUpdateOne) AddUpdatedBy(v int32) *RiskRuleUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *RiskRuleUpdateOne) ClearUpdatedBy() *RiskRuleUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *RiskRuleUpdateOne) SetDeletedBy(v uint32) *RiskRuleUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableDeletedBy(v *uint32) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *RiskRuleUpdateOne) AddDeletedBy(v int32) *RiskRuleUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *RiskRuleUpdateOne) ClearDeletedBy() *RiskRuleUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *RiskRuleUpdateOne) SetName(v string) *RiskRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableName(v *string) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *RiskRuleUpdateOne) ClearName() *RiskRuleUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *RiskRuleUpdateOne) SetDescription(v string) *RiskRuleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableDescription(v *string) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RiskRuleUpdateOne) ClearDescription() *RiskRuleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetRiskType sets the "risk_type" field.
func (_u *RiskRuleUpdateOne) SetRiskType(v riskrule.RiskType) *RiskRuleUpdateOne {
	_u.mutation.SetRiskType(v)
	return _u
}

// SetNillableRiskType sets the "risk_type" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableRiskType(v *riskrule.RiskType) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetRiskType(*v)
	}
	return _u
}

// ClearRiskType clears the value of the "risk_type" field.
func (_u *RiskRuleUpdateOne) ClearRiskType() *RiskRuleUpdateOne {
	_u.mutation.ClearRiskType()
	return _u
}

// SetDefaultLevel sets the "default_level" field.
func (_u *RiskRuleUpdateOne) SetDefaultLevel(v riskrule.DefaultLevel) *RiskRuleUpdateOne {
	_u.mutation.SetDefaultLevel(v)
	return _u
}

// SetNillableDefaultLevel sets the "default_level" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableDefaultLevel(v *riskrule.DefaultLevel) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetDefaultLevel(*v)
	}
	return _u
}

// ClearDefaultLevel clears the value of the "default_level" field.
func (_u *RiskRuleUpdateOne) ClearDefaultLevel() *RiskRuleUpdateOne {
	_u.mutation.ClearDefaultLevel()
	return _u
}

// SetCondition sets the "condition" field.
func (_u *RiskRuleUpdateOne) SetCondition(v map[string]interface{}) *RiskRuleUpdateOne {
	_u.mutation.SetCondition(v)
	return _u
}

// ClearCondition clears the value of the "condition" field.
func (_u *RiskRuleUpdateOne) ClearCondition() *RiskRuleUpdateOne {
	_u.mutation.ClearCondition()
	return _u
}

// SetActions sets the "actions" field.
func (_u *RiskRuleUpdateOne) SetActions(v []*ubapb.RiskAction) *RiskRuleUpdateOne {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *RiskRuleUpdateOne) AppendActions(v []*ubapb.RiskAction) *RiskRuleUpdateOne {
	_u.mutation.AppendActions(v)
	return _u
}

// ClearActions clears the value of the "actions" field.
func (_u *RiskRuleUpdateOne) ClearActions() *RiskRuleUpdateOne {
	_u.mutation.ClearActions()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RiskRuleUpdateOne) SetEnabled(v bool) *RiskRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableEnabled(v *bool) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// ClearEnabled clears the value of the "enabled" field.
func (_u *RiskRuleUpdateOne) ClearEnabled() *RiskRuleUpdateOne {
	_u.mutation.ClearEnabled()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *RiskRuleUpdateOne) SetPriority(v uint32) *RiskRuleUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillablePriority(v *uint32) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *RiskRuleUpdateOne) AddPriority(v int32) *RiskRuleUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// ClearPriority clears the value of the "priority" field.
func (_u *RiskRuleUpdateOne) ClearPriority() *RiskRuleUpdateOne {
	_u.mutation.ClearPriority()
	return _u
}

// SetCode sets the "code" field.
func (_u *RiskRuleUpdateOne) SetCode(v string) *RiskRuleUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableCode(v *string) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *RiskRuleUpdateOne) ClearCode() *RiskRuleUpdateOne {
	_u.mutation.ClearCode()
	return _u
}

// SetRuleExpression sets the "rule_expression" field.
func (_u *RiskRuleUpdateOne) SetRuleExpression(v string) *RiskRuleUpdateOne {
	_u.mutation.SetRuleExpression(v)
	return _u
}

// SetNillableRuleExpression sets the "rule_expression" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableRuleExpression(v *string) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetRuleExpression(*v)
	}
	return _u
}

// ClearRuleExpression clears the value of the "rule_expression" field.
func (_u *RiskRuleUpdateOne) ClearRuleExpression() *RiskRuleUpdateOne {
	_u.mutation.ClearRuleExpression()
	return _u
}

// SetRuleConfig sets the "rule_config" field.
func (_u *RiskRuleUpdateOne) SetRuleConfig(v map[string]interface{}) *RiskRuleUpdateOne {
	_u.mutation.SetRuleConfig(v)
	return _u
}

// ClearRuleConfig clears the value of the "rule_config" field.
func (_u *RiskRuleUpdateOne) ClearRuleConfig() *RiskRuleUpdateOne {
	_u.mutation.ClearRuleConfig()
	return _u
}

// SetExecMode sets the "exec_mode" field.
func (_u *RiskRuleUpdateOne) SetExecMode(v riskrule.ExecMode) *RiskRuleUpdateOne {
	_u.mutation.SetExecMode(v)
	return _u
}

// SetNillableExecMode sets the "exec_mode" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableExecMode(v *riskrule.ExecMode) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetExecMode(*v)
	}
	return _u
}

// ClearExecMode clears the value of the "exec_mode" field.
func (_u *RiskRuleUpdateOne) ClearExecMode() *RiskRuleUpdateOne {
	_u.mutation.ClearExecMode()
	return _u
}

// SetTriggerCount sets the "trigger_count" field.
func (_u *RiskRuleUpdateOne) SetTriggerCount(v uint64) *RiskRuleUpdateOne {
	_u.mutation.ResetTriggerCount()
	_u.mutation.SetTriggerCount(v)
	return _u
}

// SetNillableTriggerCount sets the "trigger_count" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableTriggerCount(v *uint64) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetTriggerCount(*v)
	}
	return _u
}

// AddTriggerCount adds value to the "trigger_count" field.
func (_u *RiskRuleUpdateOne) AddTriggerCount(v int64) *RiskRuleUpdateOne {
	_u.mutation.AddTriggerCount(v)
	return _u
}

// ClearTriggerCount clears the value of the "trigger_count" field.
func (_u *RiskRuleUpdateOne) ClearTriggerCount() *RiskRuleUpdateOne {
	_u.mutation.ClearTriggerCount()
	return _u
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_u *RiskRuleUpdateOne) SetLastTriggeredAt(v time.Time) *RiskRuleUpdateOne {
	_u.mutation.SetLastTriggeredAt(v)
	return _u
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_u *RiskRuleUpdateOne) SetNillableLastTriggeredAt(v *time.Time) *RiskRuleUpdateOne {
	if v != nil {
		_u.SetLastTriggeredAt(*v)
	}
	return _u
}

// ClearLastTriggeredAt clears the value of the "last_triggered_at" field.
func (_u *RiskRuleUpdateOne) ClearLastTriggeredAt() *RiskRuleUpdateOne {
	_u.mutation.ClearLastTriggeredAt()
	return _u
}

// Mutation returns the RiskRuleMutation object of the builder.
func (_u *RiskRuleUpdateOne) Mutation() *RiskRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the RiskRuleUpdate builder.
func (_u *RiskRuleUpdateOne) Where(ps ...predicate.RiskRule) *RiskRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RiskRuleUpdateOne) Select(field string, fields ...string) *RiskRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RiskRule entity.
func (_u *RiskRuleUpdateOne) Save(ctx context.Context) (*RiskRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RiskRuleUpdateOne) SaveX(ctx context.Context) *RiskRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RiskRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RiskRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RiskRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := riskrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RiskRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RiskType(); ok {
		if err := riskrule.RiskTypeValidator(v); err != nil {
			return &ValidationError{Name: "risk_type", err: fmt.Errorf(`ent: validator failed for field "RiskRule.risk_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultLevel(); ok {
		if err := riskrule.DefaultLevelValidator(v); err != nil {
			return &ValidationError{Name: "default_level", err: fmt.Errorf(`ent: validator failed for field "RiskRule.default_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := riskrule.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RiskRule.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecMode(); ok {
		if err := riskrule.ExecModeValidator(v); err != nil {
			return &ValidationError{Name: "exec_mode", err: fmt.Errorf(`ent: validator failed for field "RiskRule.exec_mode": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RiskRuleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RiskRuleUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RiskRuleUpdateOne) sqlSave(ctx context.Context) (_node *RiskRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(riskrule.Table, riskrule.Columns, sqlgraph.NewFieldSpec(riskrule.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RiskRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, riskrule.FieldID)
		for _, f := range fields {
			if !riskrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != riskrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(riskrule.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(riskrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(riskrule.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(riskrule.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(riskrule.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(riskrule.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(riskrule.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(riskrule.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(riskrule.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(riskrule.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(riskrule.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(riskrule.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(riskrule.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(riskrule.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(riskrule.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(riskrule.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(riskrule.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(riskrule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(riskrule.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.RiskType(); ok {
		_spec.SetField(riskrule.FieldRiskType, field.TypeEnum, value)
	}
	if _u.mutation.RiskTypeCleared() {
		_spec.ClearField(riskrule.FieldRiskType, field.TypeEnum)
	}
	if value, ok := _u.mutation.DefaultLevel(); ok {
		_spec.SetField(riskrule.FieldDefaultLevel, field.TypeEnum, value)
	}
	if _u.mutation.DefaultLevelCleared() {
		_spec.ClearField(riskrule.FieldDefaultLevel, field.TypeEnum)
	}
	if value, ok := _u.mutation.Condition(); ok {
		_spec.SetField(riskrule.FieldCondition, field.TypeJSON, value)
	}
	if _u.mutation.ConditionCleared() {
		_spec.ClearField(riskrule.FieldCondition, field.TypeJSON)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(riskrule.FieldActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, riskrule.FieldActions, value)
		})
	}
	if _u.mutation.ActionsCleared() {
		_spec.ClearField(riskrule.FieldActions, field.TypeJSON)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(riskrule.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.EnabledCleared() {
		_spec.ClearField(riskrule.FieldEnabled, field.TypeBool)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(riskrule.FieldPriority, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(riskrule.FieldPriority, field.TypeUint32, value)
	}
	if _u.mutation.PriorityCleared() {
		_spec.ClearField(riskrule.FieldPriority, field.TypeUint32)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(riskrule.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(riskrule.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.RuleExpression(); ok {
		_spec.SetField(riskrule.FieldRuleExpression, field.TypeString, value)
	}
	if _u.mutation.RuleExpressionCleared() {
		_spec.ClearField(riskrule.FieldRuleExpression, field.TypeString)
	}
	if value, ok := _u.mutation.RuleConfig(); ok {
		_spec.SetField(riskrule.FieldRuleConfig, field.TypeJSON, value)
	}
	if _u.mutation.RuleConfigCleared() {
		_spec.ClearField(riskrule.FieldRuleConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExecMode(); ok {
		_spec.SetField(riskrule.FieldExecMode, field.TypeEnum, value)
	}
	if _u.mutation.ExecModeCleared() {
		_spec.ClearField(riskrule.FieldExecMode, field.TypeEnum)
	}
	if value, ok := _u.mutation.TriggerCount(); ok {
		_spec.SetField(riskrule.FieldTriggerCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTriggerCount(); ok {
		_spec.AddField(riskrule.FieldTriggerCount, field.TypeUint64, value)
	}
	if _u.mutation.TriggerCountCleared() {
		_spec.ClearField(riskrule.FieldTriggerCount, field.TypeUint64)
	}
	if value, ok := _u.mutation.LastTriggeredAt(); ok {
		_spec.SetField(riskrule.FieldLastTriggeredAt, field.TypeTime, value)
	}
	if _u.mutation.LastTriggeredAtCleared() {
		_spec.ClearField(riskrule.FieldLastTriggeredAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RiskRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{riskrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
