// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"go-wind-uba/app/core/service/internal/data/ent/tagdefinition"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UBA标签定义表
type TagDefinition struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 标签名称，显示名称
	Name *string `json:"name,omitempty"`
	// 标签描述，详细说明
	Description *string `json:"description,omitempty"`
	// 标签分类，如用户属性、行为偏好、风险、业务等
	Category *tagdefinition.Category `json:"category,omitempty"`
	// 标签类型，如布尔、枚举、数值、字符串、列表等
	TagType *tagdefinition.TagType `json:"tag_type,omitempty"`
	// 计算规则，简化，实际可用表达式引擎，如 CEL/SQL
	Rule map[string]interface{} `json:"rule,omitempty"`
	// 取值范围，枚举型标签的允许值列表
	AllowedValues []map[string]interface{} `json:"allowed_values,omitempty"`
	// 是否系统预置，true: 系统预置，false: 用户自定义
	IsSystem *bool `json:"is_system,omitempty"`
	// 是否动态标签，true: 动态计算，false: 静态打标
	IsDynamic *bool `json:"is_dynamic,omitempty"`
	// 动态标签刷新间隔，单位秒
	RefreshIntervalSeconds *uint32 `json:"refresh_interval_seconds,omitempty"`
	// 标签唯一代码，业务唯一标识，支持英文、数字、下划线
	Code         *string `json:"code,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TagDefinition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tagdefinition.FieldRule, tagdefinition.FieldAllowedValues:
			values[i] = new([]byte)
		case tagdefinition.FieldIsSystem, tagdefinition.FieldIsDynamic:
			values[i] = new(sql.NullBool)
		case tagdefinition.FieldID, tagdefinition.FieldCreatedBy, tagdefinition.FieldUpdatedBy, tagdefinition.FieldDeletedBy, tagdefinition.FieldTenantID, tagdefinition.FieldRefreshIntervalSeconds:
			values[i] = new(sql.NullInt64)
		case tagdefinition.FieldName, tagdefinition.FieldDescription, tagdefinition.FieldCategory, tagdefinition.FieldTagType, tagdefinition.FieldCode:
			values[i] = new(sql.NullString)
		case tagdefinition.FieldCreatedAt, tagdefinition.FieldUpdatedAt, tagdefinition.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TagDefinition fields.
func (_m *TagDefinition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tagdefinition.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case tagdefinition.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case tagdefinition.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case tagdefinition.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case tagdefinition.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case tagdefinition.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case tagdefinition.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case tagdefinition.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case tagdefinition.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case tagdefinition.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case tagdefinition.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = new(tagdefinition.Category)
				*_m.Category = tagdefinition.Category(value.String)
			}
		case tagdefinition.FieldTagType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag_type", values[i])
			} else if value.Valid {
				_m.TagType = new(tagdefinition.TagType)
				*_m.TagType = tagdefinition.TagType(value.String)
			}
		case tagdefinition.FieldRule:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rule", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Rule); err != nil {
					return fmt.Errorf("unmarshal field rule: %w", err)
				}
			}
		case tagdefinition.FieldAllowedValues:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_values", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedValues); err != nil {
					return fmt.Errorf("unmarshal field allowed_values: %w", err)
				}
			}
		case tagdefinition.FieldIsSystem:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_system", values[i])
			} else if value.Valid {
				_m.IsSystem = new(bool)
				*_m.IsSystem = value.Bool
			}
		case tagdefinition.FieldIsDynamic:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_dynamic", values[i])
			} else if value.Valid {
				_m.IsDynamic = new(bool)
				*_m.IsDynamic = value.Bool
			}
		case tagdefinition.FieldRefreshIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_interval_seconds", values[i])
			} else if value.Valid {
				_m.RefreshIntervalSeconds = new(uint32)
				*_m.RefreshIntervalSeconds = uint32(value.Int64)
			}
		case tagdefinition.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = new(string)
				*_m.Code = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TagDefinition.
// This includes values selected through modifiers, order, etc.
func (_m *TagDefinition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TagDefinition.
// Note that you need to call TagDefinition.Unwrap() before calling this method if this TagDefinition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TagDefinition) Update() *TagDefinitionUpdateOne {
	return NewTagDefinitionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TagDefinition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TagDefinition) Unwrap() *TagDefinition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TagDefinition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TagDefinition) String() string {
	var builder strings.Builder
	builder.WriteString("TagDefinition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Category; v != nil {
		builder.WriteString("category=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TagType; v != nil {
		builder.WriteString("tag_type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("rule=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rule))
	builder.WriteString(", ")
	builder.WriteString("allowed_values=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedValues))
	builder.WriteString(", ")
	if v := _m.IsSystem; v != nil {
		builder.WriteString("is_system=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IsDynamic; v != nil {
		builder.WriteString("is_dynamic=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RefreshIntervalSeconds; v != nil {
		builder.WriteString("refresh_interval_seconds=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Code; v != nil {
		builder.WriteString("code=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// TagDefinitions is a parsable slice of TagDefinition.
type TagDefinitions []*TagDefinition
