// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	servicev1 "go-wind-uba/api/gen/go/uba/service/v1"
	"go-wind-uba/app/core/service/internal/data/ent/tagdefinition"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TagDefinitionCreate is the builder for creating a TagDefinition entity.
type TagDefinitionCreate struct {
	config
	mutation *TagDefinitionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TagDefinitionCreate) SetCreatedAt(v time.Time) *TagDefinitionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableCreatedAt(v *time.Time) *TagDefinitionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TagDefinitionCreate) SetUpdatedAt(v time.Time) *TagDefinitionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableUpdatedAt(v *time.Time) *TagDefinitionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TagDefinitionCreate) SetDeletedAt(v time.Time) *TagDefinitionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableDeletedAt(v *time.Time) *TagDefinitionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *TagDefinitionCreate) SetCreatedBy(v uint32) *TagDefinitionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableCreatedBy(v *uint32) *TagDefinitionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *TagDefinitionCreate) SetUpdatedBy(v uint32) *TagDefinitionCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableUpdatedBy(v *uint32) *TagDefinitionCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *TagDefinitionCreate) SetDeletedBy(v uint32) *TagDefinitionCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableDeletedBy(v *uint32) *TagDefinitionCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *TagDefinitionCreate) SetTenantID(v uint32) *TagDefinitionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableTenantID(v *uint32) *TagDefinitionCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *TagDefinitionCreate) SetName(v string) *TagDefinitionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableName(v *string) *TagDefinitionCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *TagDefinitionCreate) SetDescription(v string) *TagDefinitionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableDescription(v *string) *TagDefinitionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *TagDefinitionCreate) SetCategory(v tagdefinition.Category) *TagDefinitionCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableCategory(v *tagdefinition.Category) *TagDefinitionCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetTagType sets the "tag_type" field.
func (_c *TagDefinitionCreate) SetTagType(v tagdefinition.TagType) *TagDefinitionCreate {
	_c.mutation.SetTagType(v)
	return _c
}

// SetNillableTagType sets the "tag_type" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableTagType(v *tagdefinition.TagType) *TagDefinitionCreate {
	if v != nil {
		_c.SetTagType(*v)
	}
	return _c
}

// SetRule sets the "rule" field.
func (_c *TagDefinitionCreate) SetRule(v *servicev1.TagRule) *TagDefinitionCreate {
	_c.mutation.SetRule(v)
	return _c
}

// SetAllowedValues sets the "allowed_values" field.
func (_c *TagDefinitionCreate) SetAllowedValues(v []*servicev1.TagValue) *TagDefinitionCreate {
	_c.mutation.SetAllowedValues(v)
	return _c
}

// SetIsSystem sets the "is_system" field.
func (_c *TagDefinitionCreate) SetIsSystem(v bool) *TagDefinitionCreate {
	_c.mutation.SetIsSystem(v)
	return _c
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableIsSystem(v *bool) *TagDefinitionCreate {
	if v != nil {
		_c.SetIsSystem(*v)
	}
	return _c
}

// SetIsDynamic sets the "is_dynamic" field.
func (_c *TagDefinitionCreate) SetIsDynamic(v bool) *TagDefinitionCreate {
	_c.mutation.SetIsDynamic(v)
	return _c
}

// SetNillableIsDynamic sets the "is_dynamic" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableIsDynamic(v *bool) *TagDefinitionCreate {
	if v != nil {
		_c.SetIsDynamic(*v)
	}
	return _c
}

// SetRefreshIntervalSeconds sets the "refresh_interval_seconds" field.
func (_c *TagDefinitionCreate) SetRefreshIntervalSeconds(v uint32) *TagDefinitionCreate {
	_c.mutation.SetRefreshIntervalSeconds(v)
	return _c
}

// SetNillableRefreshIntervalSeconds sets the "refresh_interval_seconds" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableRefreshIntervalSeconds(v *uint32) *TagDefinitionCreate {
	if v != nil {
		_c.SetRefreshIntervalSeconds(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *TagDefinitionCreate) SetCode(v string) *TagDefinitionCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *TagDefinitionCreate) SetNillableCode(v *string) *TagDefinitionCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TagDefinitionCreate) SetID(v uint32) *TagDefinitionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TagDefinitionMutation object of the builder.
func (_c *TagDefinitionCreate) Mutation() *TagDefinitionMutation {
	return _c.mutation
}

// Save creates the TagDefinition in the database.
func (_c *TagDefinitionCreate) Save(ctx context.Context) (*TagDefinition, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TagDefinitionCreate) SaveX(ctx context.Context) *TagDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TagDefinitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TagDefinitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TagDefinitionCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := tagdefinition.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		v := tagdefinition.DefaultIsSystem
		_c.mutation.SetIsSystem(v)
	}
	if _, ok := _c.mutation.IsDynamic(); !ok {
		v := tagdefinition.DefaultIsDynamic
		_c.mutation.SetIsDynamic(v)
	}
	if _, ok := _c.mutation.RefreshIntervalSeconds(); !ok {
		v := tagdefinition.DefaultRefreshIntervalSeconds
		_c.mutation.SetRefreshIntervalSeconds(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TagDefinitionCreate) check() error {
	if v, ok := _c.mutation.Name(); ok {
		if err := tagdefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TagDefinition.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := tagdefinition.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "TagDefinition.category": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TagType(); ok {
		if err := tagdefinition.TagTypeValidator(v); err != nil {
			return &ValidationError{Name: "tag_type", err: fmt.Errorf(`ent: validator failed for field "TagDefinition.tag_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Rule(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "rule", err: fmt.Errorf(`ent: validator failed for field "TagDefinition.rule": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := tagdefinition.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "TagDefinition.code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := tagdefinition.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TagDefinition.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TagDefinitionCreate) sqlSave(ctx context.Context) (*TagDefinition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TagDefinitionCreate) createSpec() (*TagDefinition, *sqlgraph.CreateSpec) {
	var (
		_node = &TagDefinition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tagdefinition.Table, sqlgraph.NewFieldSpec(tagdefinition.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tagdefinition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tagdefinition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(tagdefinition.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(tagdefinition.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(tagdefinition.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(tagdefinition.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(tagdefinition.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tagdefinition.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(tagdefinition.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(tagdefinition.FieldCategory, field.TypeEnum, value)
		_node.Category = &value
	}
	if value, ok := _c.mutation.TagType(); ok {
		_spec.SetField(tagdefinition.FieldTagType, field.TypeEnum, value)
		_node.TagType = &value
	}
	if value, ok := _c.mutation.Rule(); ok {
		_spec.SetField(tagdefinition.FieldRule, field.TypeJSON, value)
		_node.Rule = value
	}
	if value, ok := _c.mutation.AllowedValues(); ok {
		_spec.SetField(tagdefinition.FieldAllowedValues, field.TypeJSON, value)
		_node.AllowedValues = value
	}
	if value, ok := _c.mutation.IsSystem(); ok {
		_spec.SetField(tagdefinition.FieldIsSystem, field.TypeBool, value)
		_node.IsSystem = &value
	}
	if value, ok := _c.mutation.IsDynamic(); ok {
		_spec.SetField(tagdefinition.FieldIsDynamic, field.TypeBool, value)
		_node.IsDynamic = &value
	}
	if value, ok := _c.mutation.RefreshIntervalSeconds(); ok {
		_spec.SetField(tagdefinition.FieldRefreshIntervalSeconds, field.TypeUint32, value)
		_node.RefreshIntervalSeconds = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(tagdefinition.FieldCode, field.TypeString, value)
		_node.Code = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TagDefinition.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TagDefinitionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TagDefinitionCreate) OnConflict(opts ...sql.ConflictOption) *TagDefinitionUpsertOne {
	_c.conflict = opts
	return &TagDefinitionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TagDefinition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TagDefinitionCreate) OnConflictColumns(columns ...string) *TagDefinitionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TagDefinitionUpsertOne{
		create: _c,
	}
}

type (
	// TagDefinitionUpsertOne is the builder for "upsert"-ing
	//  one TagDefinition node.
	TagDefinitionUpsertOne struct {
		create *TagDefinitionCreate
	}

	// TagDefinitionUpsert is the "OnConflict" setter.
	TagDefinitionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TagDefinitionUpsert) SetUpdatedAt(v time.Time) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateUpdatedAt() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TagDefinitionUpsert) ClearUpdatedAt() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TagDefinitionUpsert) SetDeletedAt(v time.Time) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateDeletedAt() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TagDefinitionUpsert) ClearDeletedAt() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *TagDefinitionUpsert) SetCreatedBy(v uint32) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateCreatedBy() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *TagDefinitionUpsert) AddCreatedBy(v uint32) *TagDefinitionUpsert {
	u.Add(tagdefinition.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TagDefinitionUpsert) ClearCreatedBy() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TagDefinitionUpsert) SetUpdatedBy(v uint32) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateUpdatedBy() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *TagDefinitionUpsert) AddUpdatedBy(v uint32) *TagDefinitionUpsert {
	u.Add(tagdefinition.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TagDefinitionUpsert) ClearUpdatedBy() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *TagDefinitionUpsert) SetDeletedBy(v uint32) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateDeletedBy() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *TagDefinitionUpsert) AddDeletedBy(v uint32) *TagDefinitionUpsert {
	u.Add(tagdefinition.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *TagDefinitionUpsert) ClearDeletedBy() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldDeletedBy)
	return u
}

// SetName sets the "name" field.
func (u *TagDefinitionUpsert) SetName(v string) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateName() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *TagDefinitionUpsert) ClearName() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *TagDefinitionUpsert) SetDescription(v string) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateDescription() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *TagDefinitionUpsert) ClearDescription() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldDescription)
	return u
}

// SetCategory sets the "category" field.
func (u *TagDefinitionUpsert) SetCategory(v tagdefinition.Category) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateCategory() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldCategory)
	return u
}

// ClearCategory clears the value of the "category" field.
func (u *TagDefinitionUpsert) ClearCategory() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldCategory)
	return u
}

// SetTagType sets the "tag_type" field.
func (u *TagDefinitionUpsert) SetTagType(v tagdefinition.TagType) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldTagType, v)
	return u
}

// UpdateTagType sets the "tag_type" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateTagType() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldTagType)
	return u
}

// ClearTagType clears the value of the "tag_type" field.
func (u *TagDefinitionUpsert) ClearTagType() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldTagType)
	return u
}

// SetRule sets the "rule" field.
func (u *TagDefinitionUpsert) SetRule(v *servicev1.TagRule) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldRule, v)
	return u
}

// UpdateRule sets the "rule" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateRule() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldRule)
	return u
}

// ClearRule clears the value of the "rule" field.
func (u *TagDefinitionUpsert) ClearRule() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldRule)
	return u
}

// SetAllowedValues sets the "allowed_values" field.
func (u *TagDefinitionUpsert) SetAllowedValues(v []*servicev1.TagValue) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldAllowedValues, v)
	return u
}

// UpdateAllowedValues sets the "allowed_values" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateAllowedValues() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldAllowedValues)
	return u
}

// ClearAllowedValues clears the value of the "allowed_values" field.
func (u *TagDefinitionUpsert) ClearAllowedValues() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldAllowedValues)
	return u
}

// SetIsSystem sets the "is_system" field.
func (u *TagDefinitionUpsert) SetIsSystem(v bool) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldIsSystem, v)
	return u
}

// UpdateIsSystem sets the "is_system" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateIsSystem() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldIsSystem)
	return u
}

// ClearIsSystem clears the value of the "is_system" field.
func (u *TagDefinitionUpsert) ClearIsSystem() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldIsSystem)
	return u
}

// SetIsDynamic sets the "is_dynamic" field.
func (u *TagDefinitionUpsert) SetIsDynamic(v bool) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldIsDynamic, v)
	return u
}

// UpdateIsDynamic sets the "is_dynamic" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateIsDynamic() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldIsDynamic)
	return u
}

// ClearIsDynamic clears the value of the "is_dynamic" field.
func (u *TagDefinitionUpsert) ClearIsDynamic() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldIsDynamic)
	return u
}

// SetRefreshIntervalSeconds sets the "refresh_interval_seconds" field.
func (u *TagDefinitionUpsert) SetRefreshIntervalSeconds(v uint32) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldRefreshIntervalSeconds, v)
	return u
}

// UpdateRefreshIntervalSeconds sets the "refresh_interval_seconds" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateRefreshIntervalSeconds() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldRefreshIntervalSeconds)
	return u
}

// AddRefreshIntervalSeconds adds v to the "refresh_interval_seconds" field.
func (u *TagDefinitionUpsert) AddRefreshIntervalSeconds(v uint32) *TagDefinitionUpsert {
	u.Add(tagdefinition.FieldRefreshIntervalSeconds, v)
	return u
}

// ClearRefreshIntervalSeconds clears the value of the "refresh_interval_seconds" field.
func (u *TagDefinitionUpsert) ClearRefreshIntervalSeconds() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldRefreshIntervalSeconds)
	return u
}

// SetCode sets the "code" field.
func (u *TagDefinitionUpsert) SetCode(v string) *TagDefinitionUpsert {
	u.Set(tagdefinition.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TagDefinitionUpsert) UpdateCode() *TagDefinitionUpsert {
	u.SetExcluded(tagdefinition.FieldCode)
	return u
}

// ClearCode clears the value of the "code" field.
func (u *TagDefinitionUpsert) ClearCode() *TagDefinitionUpsert {
	u.SetNull(tagdefinition.FieldCode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TagDefinition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tagdefinition.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TagDefinitionUpsertOne) UpdateNewValues() *TagDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(tagdefinition.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(tagdefinition.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(tagdefinition.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TagDefinition.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TagDefinitionUpsertOne) Ignore() *TagDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TagDefinitionUpsertOne) DoNothing() *TagDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TagDefinitionCreate.OnConflict
// documentation for more info.
func (u *TagDefinitionUpsertOne) Update(set func(*TagDefinitionUpsert)) *TagDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TagDefinitionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TagDefinitionUpsertOne) SetUpdatedAt(v time.Time) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateUpdatedAt() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TagDefinitionUpsertOne) ClearUpdatedAt() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TagDefinitionUpsertOne) SetDeletedAt(v time.Time) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateDeletedAt() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TagDefinitionUpsertOne) ClearDeletedAt() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *TagDefinitionUpsertOne) SetCreatedBy(v uint32) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *TagDefinitionUpsertOne) AddCreatedBy(v uint32) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateCreatedBy() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TagDefinitionUpsertOne) ClearCreatedBy() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TagDefinitionUpsertOne) SetUpdatedBy(v uint32) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *TagDefinitionUpsertOne) AddUpdatedBy(v uint32) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateUpdatedBy() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TagDefinitionUpsertOne) ClearUpdatedBy() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *TagDefinitionUpsertOne) SetDeletedBy(v uint32) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *TagDefinitionUpsertOne) AddDeletedBy(v uint32) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateDeletedBy() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *TagDefinitionUpsertOne) ClearDeletedBy() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearDeletedBy()
	})
}

// SetName sets the "name" field.
func (u *TagDefinitionUpsertOne) SetName(v string) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateName() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *TagDefinitionUpsertOne) ClearName() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *TagDefinitionUpsertOne) SetDescription(v string) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateDescription() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TagDefinitionUpsertOne) ClearDescription() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearDescription()
	})
}

// SetCategory sets the "category" field.
func (u *TagDefinitionUpsertOne) SetCategory(v tagdefinition.Category) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateCategory() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateCategory()
	})
}

// ClearCategory clears the value of the "category" field.
func (u *TagDefinitionUpsertOne) ClearCategory() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearCategory()
	})
}

// SetTagType sets the "tag_type" field.
func (u *TagDefinitionUpsertOne) SetTagType(v tagdefinition.TagType) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetTagType(v)
	})
}

// UpdateTagType sets the "tag_type" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateTagType() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateTagType()
	})
}

// ClearTagType clears the value of the "tag_type" field.
func (u *TagDefinitionUpsertOne) ClearTagType() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearTagType()
	})
}

// SetRule sets the "rule" field.
func (u *TagDefinitionUpsertOne) SetRule(v *servicev1.TagRule) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetRule(v)
	})
}

// UpdateRule sets the "rule" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateRule() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateRule()
	})
}

// ClearRule clears the value of the "rule" field.
func (u *TagDefinitionUpsertOne) ClearRule() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearRule()
	})
}

// SetAllowedValues sets the "allowed_values" field.
func (u *TagDefinitionUpsertOne) SetAllowedValues(v []*servicev1.TagValue) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetAllowedValues(v)
	})
}

// UpdateAllowedValues sets the "allowed_values" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateAllowedValues() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateAllowedValues()
	})
}

// ClearAllowedValues clears the value of the "allowed_values" field.
func (u *TagDefinitionUpsertOne) ClearAllowedValues() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearAllowedValues()
	})
}

// SetIsSystem sets the "is_system" field.
func (u *TagDefinitionUpsertOne) SetIsSystem(v bool) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetIsSystem(v)
	})
}

// UpdateIsSystem sets the "is_system" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateIsSystem() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateIsSystem()
	})
}

// ClearIsSystem clears the value of the "is_system" field.
func (u *TagDefinitionUpsertOne) ClearIsSystem() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearIsSystem()
	})
}

// SetIsDynamic sets the "is_dynamic" field.
func (u *TagDefinitionUpsertOne) SetIsDynamic(v bool) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetIsDynamic(v)
	})
}

// UpdateIsDynamic sets the "is_dynamic" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateIsDynamic() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateIsDynamic()
	})
}

// ClearIsDynamic clears the value of the "is_dynamic" field.
func (u *TagDefinitionUpsertOne) ClearIsDynamic() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearIsDynamic()
	})
}

// SetRefreshIntervalSeconds sets the "refresh_interval_seconds" field.
func (u *TagDefinitionUpsertOne) SetRefreshIntervalSeconds(v uint32) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetRefreshIntervalSeconds(v)
	})
}

// AddRefreshIntervalSeconds adds v to the "refresh_interval_seconds" field.
func (u *TagDefinitionUpsertOne) AddRefreshIntervalSeconds(v uint32) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.AddRefreshIntervalSeconds(v)
	})
}

// UpdateRefreshIntervalSeconds sets the "refresh_interval_seconds" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateRefreshIntervalSeconds() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateRefreshIntervalSeconds()
	})
}

// ClearRefreshIntervalSeconds clears the value of the "refresh_interval_seconds" field.
func (u *TagDefinitionUpsertOne) ClearRefreshIntervalSeconds() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearRefreshIntervalSeconds()
	})
}

// SetCode sets the "code" field.
func (u *TagDefinitionUpsertOne) SetCode(v string) *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TagDefinitionUpsertOne) UpdateCode() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *TagDefinitionUpsertOne) ClearCode() *TagDefinitionUpsertOne {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearCode()
	})
}

// Exec executes the query.
func (u *TagDefinitionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TagDefinitionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TagDefinitionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TagDefinitionUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TagDefinitionUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TagDefinitionCreateBulk is the builder for creating many TagDefinition entities in bulk.
type TagDefinitionCreateBulk struct {
	config
	err      error
	builders []*TagDefinitionCreate
	conflict []sql.ConflictOption
}

// Save creates the TagDefinition entities in the database.
func (_c *TagDefinitionCreateBulk) Save(ctx context.Context) ([]*TagDefinition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TagDefinition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TagDefinitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TagDefinitionCreateBulk) SaveX(ctx context.Context) []*TagDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TagDefinitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TagDefinitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TagDefinition.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TagDefinitionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TagDefinitionCreateBulk) OnConflict(opts ...sql.ConflictOption) *TagDefinitionUpsertBulk {
	_c.conflict = opts
	return &TagDefinitionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TagDefinition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TagDefinitionCreateBulk) OnConflictColumns(columns ...string) *TagDefinitionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TagDefinitionUpsertBulk{
		create: _c,
	}
}

// TagDefinitionUpsertBulk is the builder for "upsert"-ing
// a bulk of TagDefinition nodes.
type TagDefinitionUpsertBulk struct {
	create *TagDefinitionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TagDefinition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tagdefinition.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TagDefinitionUpsertBulk) UpdateNewValues() *TagDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(tagdefinition.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(tagdefinition.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(tagdefinition.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TagDefinition.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TagDefinitionUpsertBulk) Ignore() *TagDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TagDefinitionUpsertBulk) DoNothing() *TagDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TagDefinitionCreateBulk.OnConflict
// documentation for more info.
func (u *TagDefinitionUpsertBulk) Update(set func(*TagDefinitionUpsert)) *TagDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TagDefinitionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TagDefinitionUpsertBulk) SetUpdatedAt(v time.Time) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateUpdatedAt() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TagDefinitionUpsertBulk) ClearUpdatedAt() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TagDefinitionUpsertBulk) SetDeletedAt(v time.Time) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateDeletedAt() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TagDefinitionUpsertBulk) ClearDeletedAt() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *TagDefinitionUpsertBulk) SetCreatedBy(v uint32) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *TagDefinitionUpsertBulk) AddCreatedBy(v uint32) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateCreatedBy() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TagDefinitionUpsertBulk) ClearCreatedBy() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TagDefinitionUpsertBulk) SetUpdatedBy(v uint32) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *TagDefinitionUpsertBulk) AddUpdatedBy(v uint32) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateUpdatedBy() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TagDefinitionUpsertBulk) ClearUpdatedBy() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *TagDefinitionUpsertBulk) SetDeletedBy(v uint32) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *TagDefinitionUpsertBulk) AddDeletedBy(v uint32) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateDeletedBy() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *TagDefinitionUpsertBulk) ClearDeletedBy() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearDeletedBy()
	})
}

// SetName sets the "name" field.
func (u *TagDefinitionUpsertBulk) SetName(v string) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateName() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *TagDefinitionUpsertBulk) ClearName() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *TagDefinitionUpsertBulk) SetDescription(v string) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateDescription() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TagDefinitionUpsertBulk) ClearDescription() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearDescription()
	})
}

// SetCategory sets the "category" field.
func (u *TagDefinitionUpsertBulk) SetCategory(v tagdefinition.Category) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateCategory() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateCategory()
	})
}

// ClearCategory clears the value of the "category" field.
func (u *TagDefinitionUpsertBulk) ClearCategory() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearCategory()
	})
}

// SetTagType sets the "tag_type" field.
func (u *TagDefinitionUpsertBulk) SetTagType(v tagdefinition.TagType) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetTagType(v)
	})
}

// UpdateTagType sets the "tag_type" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateTagType() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateTagType()
	})
}

// ClearTagType clears the value of the "tag_type" field.
func (u *TagDefinitionUpsertBulk) ClearTagType() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearTagType()
	})
}

// SetRule sets the "rule" field.
func (u *TagDefinitionUpsertBulk) SetRule(v *servicev1.TagRule) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetRule(v)
	})
}

// UpdateRule sets the "rule" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateRule() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateRule()
	})
}

// ClearRule clears the value of the "rule" field.
func (u *TagDefinitionUpsertBulk) ClearRule() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearRule()
	})
}

// SetAllowedValues sets the "allowed_values" field.
func (u *TagDefinitionUpsertBulk) SetAllowedValues(v []*servicev1.TagValue) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetAllowedValues(v)
	})
}

// UpdateAllowedValues sets the "allowed_values" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateAllowedValues() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateAllowedValues()
	})
}

// ClearAllowedValues clears the value of the "allowed_values" field.
func (u *TagDefinitionUpsertBulk) ClearAllowedValues() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearAllowedValues()
	})
}

// SetIsSystem sets the "is_system" field.
func (u *TagDefinitionUpsertBulk) SetIsSystem(v bool) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetIsSystem(v)
	})
}

// UpdateIsSystem sets the "is_system" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateIsSystem() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateIsSystem()
	})
}

// ClearIsSystem clears the value of the "is_system" field.
func (u *TagDefinitionUpsertBulk) ClearIsSystem() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearIsSystem()
	})
}

// SetIsDynamic sets the "is_dynamic" field.
func (u *TagDefinitionUpsertBulk) SetIsDynamic(v bool) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetIsDynamic(v)
	})
}

// UpdateIsDynamic sets the "is_dynamic" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateIsDynamic() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateIsDynamic()
	})
}

// ClearIsDynamic clears the value of the "is_dynamic" field.
func (u *TagDefinitionUpsertBulk) ClearIsDynamic() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearIsDynamic()
	})
}

// SetRefreshIntervalSeconds sets the "refresh_interval_seconds" field.
func (u *TagDefinitionUpsertBulk) SetRefreshIntervalSeconds(v uint32) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetRefreshIntervalSeconds(v)
	})
}

// AddRefreshIntervalSeconds adds v to the "refresh_interval_seconds" field.
func (u *TagDefinitionUpsertBulk) AddRefreshIntervalSeconds(v uint32) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.AddRefreshIntervalSeconds(v)
	})
}

// UpdateRefreshIntervalSeconds sets the "refresh_interval_seconds" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateRefreshIntervalSeconds() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateRefreshIntervalSeconds()
	})
}

// ClearRefreshIntervalSeconds clears the value of the "refresh_interval_seconds" field.
func (u *TagDefinitionUpsertBulk) ClearRefreshIntervalSeconds() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearRefreshIntervalSeconds()
	})
}

// SetCode sets the "code" field.
func (u *TagDefinitionUpsertBulk) SetCode(v string) *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TagDefinitionUpsertBulk) UpdateCode() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *TagDefinitionUpsertBulk) ClearCode() *TagDefinitionUpsertBulk {
	return u.Update(func(s *TagDefinitionUpsert) {
		s.ClearCode()
	})
}

// Exec executes the query.
func (u *TagDefinitionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TagDefinitionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TagDefinitionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TagDefinitionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
