// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sync"

	"entgo.io/ent/dialect"
)

// Tx is a transactional client that is created by calling Client.Tx().
type Tx struct {
	config
	// Api is the client for interacting with the Api builders.
	Api *APIClient
	// ApiAuditLog is the client for interacting with the ApiAuditLog builders.
	ApiAuditLog *ApiAuditLogClient
	// Application is the client for interacting with the Application builders.
	Application *ApplicationClient
	// DataAccessAuditLog is the client for interacting with the DataAccessAuditLog builders.
	DataAccessAuditLog *DataAccessAuditLogClient
	// DictEntry is the client for interacting with the DictEntry builders.
	DictEntry *DictEntryClient
	// DictEntryI18n is the client for interacting with the DictEntryI18n builders.
	DictEntryI18n *DictEntryI18nClient
	// DictType is the client for interacting with the DictType builders.
	DictType *DictTypeClient
	// DictTypeI18n is the client for interacting with the DictTypeI18n builders.
	DictTypeI18n *DictTypeI18nClient
	// File is the client for interacting with the File builders.
	File *FileClient
	// IDMapping is the client for interacting with the IDMapping builders.
	IDMapping *IDMappingClient
	// InternalMessage is the client for interacting with the InternalMessage builders.
	InternalMessage *InternalMessageClient
	// InternalMessageCategory is the client for interacting with the InternalMessageCategory builders.
	InternalMessageCategory *InternalMessageCategoryClient
	// InternalMessageRecipient is the client for interacting with the InternalMessageRecipient builders.
	InternalMessageRecipient *InternalMessageRecipientClient
	// Language is the client for interacting with the Language builders.
	Language *LanguageClient
	// LoginAuditLog is the client for interacting with the LoginAuditLog builders.
	LoginAuditLog *LoginAuditLogClient
	// LoginPolicy is the client for interacting with the LoginPolicy builders.
	LoginPolicy *LoginPolicyClient
	// Menu is the client for interacting with the Menu builders.
	Menu *MenuClient
	// OperationAuditLog is the client for interacting with the OperationAuditLog builders.
	OperationAuditLog *OperationAuditLogClient
	// OrgUnit is the client for interacting with the OrgUnit builders.
	OrgUnit *OrgUnitClient
	// Permission is the client for interacting with the Permission builders.
	Permission *PermissionClient
	// PermissionApi is the client for interacting with the PermissionApi builders.
	PermissionApi *PermissionApiClient
	// PermissionAuditLog is the client for interacting with the PermissionAuditLog builders.
	PermissionAuditLog *PermissionAuditLogClient
	// PermissionGroup is the client for interacting with the PermissionGroup builders.
	PermissionGroup *PermissionGroupClient
	// PermissionMenu is the client for interacting with the PermissionMenu builders.
	PermissionMenu *PermissionMenuClient
	// PermissionPolicy is the client for interacting with the PermissionPolicy builders.
	PermissionPolicy *PermissionPolicyClient
	// PolicyEvaluationLog is the client for interacting with the PolicyEvaluationLog builders.
	PolicyEvaluationLog *PolicyEvaluationLogClient
	// Position is the client for interacting with the Position builders.
	Position *PositionClient
	// RiskRule is the client for interacting with the RiskRule builders.
	RiskRule *RiskRuleClient
	// RiskRuleCondition is the client for interacting with the RiskRuleCondition builders.
	RiskRuleCondition *RiskRuleConditionClient
	// RiskRuleVersion is the client for interacting with the RiskRuleVersion builders.
	RiskRuleVersion *RiskRuleVersionClient
	// Role is the client for interacting with the Role builders.
	Role *RoleClient
	// RoleMetadata is the client for interacting with the RoleMetadata builders.
	RoleMetadata *RoleMetadataClient
	// RolePermission is the client for interacting with the RolePermission builders.
	RolePermission *RolePermissionClient
	// TagDefinition is the client for interacting with the TagDefinition builders.
	TagDefinition *TagDefinitionClient
	// TagValue is the client for interacting with the TagValue builders.
	TagValue *TagValueClient
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
	// Tenant is the client for interacting with the Tenant builders.
	Tenant *TenantClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserCredential is the client for interacting with the UserCredential builders.
	UserCredential *UserCredentialClient
	// UserOrgUnit is the client for interacting with the UserOrgUnit builders.
	UserOrgUnit *UserOrgUnitClient
	// UserPosition is the client for interacting with the UserPosition builders.
	UserPosition *UserPositionClient
	// UserRole is the client for interacting with the UserRole builders.
	UserRole *UserRoleClient
	// UserTag is the client for interacting with the UserTag builders.
	UserTag *UserTagClient
	// Webhook is the client for interacting with the Webhook builders.
	Webhook *WebhookClient

	// lazily loaded.
	client     *Client
	clientOnce sync.Once
	// ctx lives for the life of the transaction. It is
	// the same context used by the underlying connection.
	ctx context.Context
}

type (
	// Committer is the interface that wraps the Commit method.
	Committer interface {
		Commit(context.Context, *Tx) error
	}

	// The CommitFunc type is an adapter to allow the use of ordinary
	// function as a Committer. If f is a function with the appropriate
	// signature, CommitFunc(f) is a Committer that calls f.
	CommitFunc func(context.Context, *Tx) error

	// CommitHook defines the "commit middleware". A function that gets a Committer
	// and returns a Committer. For example:
	//
	//	hook := func(next ent.Committer) ent.Committer {
	//		return ent.CommitFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Commit(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	CommitHook func(Committer) Committer
)

// Commit calls f(ctx, m).
func (f CommitFunc) Commit(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Commit commits the transaction.
func (tx *Tx) Commit() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Committer = CommitFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Commit()
	})
	txDriver.mu.Lock()
	hooks := append([]CommitHook(nil), txDriver.onCommit...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Commit(tx.ctx, tx)
}

// OnCommit adds a hook to call on commit.
func (tx *Tx) OnCommit(f CommitHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onCommit = append(txDriver.onCommit, f)
	txDriver.mu.Unlock()
}

type (
	// Rollbacker is the interface that wraps the Rollback method.
	Rollbacker interface {
		Rollback(context.Context, *Tx) error
	}

	// The RollbackFunc type is an adapter to allow the use of ordinary
	// function as a Rollbacker. If f is a function with the appropriate
	// signature, RollbackFunc(f) is a Rollbacker that calls f.
	RollbackFunc func(context.Context, *Tx) error

	// RollbackHook defines the "rollback middleware". A function that gets a Rollbacker
	// and returns a Rollbacker. For example:
	//
	//	hook := func(next ent.Rollbacker) ent.Rollbacker {
	//		return ent.RollbackFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Rollback(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	RollbackHook func(Rollbacker) Rollbacker
)

// Rollback calls f(ctx, m).
func (f RollbackFunc) Rollback(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Rollback rollbacks the transaction.
func (tx *Tx) Rollback() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Rollbacker = RollbackFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Rollback()
	})
	txDriver.mu.Lock()
	hooks := append([]RollbackHook(nil), txDriver.onRollback...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Rollback(tx.ctx, tx)
}

// OnRollback adds a hook to call on rollback.
func (tx *Tx) OnRollback(f RollbackHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onRollback = append(txDriver.onRollback, f)
	txDriver.mu.Unlock()
}

// Client returns a Client that binds to current transaction.
func (tx *Tx) Client() *Client {
	tx.clientOnce.Do(func() {
		tx.client = &Client{config: tx.config}
		tx.client.init()
	})
	return tx.client
}

func (tx *Tx) init() {
	tx.Api = NewAPIClient(tx.config)
	tx.ApiAuditLog = NewApiAuditLogClient(tx.config)
	tx.Application = NewApplicationClient(tx.config)
	tx.DataAccessAuditLog = NewDataAccessAuditLogClient(tx.config)
	tx.DictEntry = NewDictEntryClient(tx.config)
	tx.DictEntryI18n = NewDictEntryI18nClient(tx.config)
	tx.DictType = NewDictTypeClient(tx.config)
	tx.DictTypeI18n = NewDictTypeI18nClient(tx.config)
	tx.File = NewFileClient(tx.config)
	tx.IDMapping = NewIDMappingClient(tx.config)
	tx.InternalMessage = NewInternalMessageClient(tx.config)
	tx.InternalMessageCategory = NewInternalMessageCategoryClient(tx.config)
	tx.InternalMessageRecipient = NewInternalMessageRecipientClient(tx.config)
	tx.Language = NewLanguageClient(tx.config)
	tx.LoginAuditLog = NewLoginAuditLogClient(tx.config)
	tx.LoginPolicy = NewLoginPolicyClient(tx.config)
	tx.Menu = NewMenuClient(tx.config)
	tx.OperationAuditLog = NewOperationAuditLogClient(tx.config)
	tx.OrgUnit = NewOrgUnitClient(tx.config)
	tx.Permission = NewPermissionClient(tx.config)
	tx.PermissionApi = NewPermissionApiClient(tx.config)
	tx.PermissionAuditLog = NewPermissionAuditLogClient(tx.config)
	tx.PermissionGroup = NewPermissionGroupClient(tx.config)
	tx.PermissionMenu = NewPermissionMenuClient(tx.config)
	tx.PermissionPolicy = NewPermissionPolicyClient(tx.config)
	tx.PolicyEvaluationLog = NewPolicyEvaluationLogClient(tx.config)
	tx.Position = NewPositionClient(tx.config)
	tx.RiskRule = NewRiskRuleClient(tx.config)
	tx.RiskRuleCondition = NewRiskRuleConditionClient(tx.config)
	tx.RiskRuleVersion = NewRiskRuleVersionClient(tx.config)
	tx.Role = NewRoleClient(tx.config)
	tx.RoleMetadata = NewRoleMetadataClient(tx.config)
	tx.RolePermission = NewRolePermissionClient(tx.config)
	tx.TagDefinition = NewTagDefinitionClient(tx.config)
	tx.TagValue = NewTagValueClient(tx.config)
	tx.Task = NewTaskClient(tx.config)
	tx.Tenant = NewTenantClient(tx.config)
	tx.User = NewUserClient(tx.config)
	tx.UserCredential = NewUserCredentialClient(tx.config)
	tx.UserOrgUnit = NewUserOrgUnitClient(tx.config)
	tx.UserPosition = NewUserPositionClient(tx.config)
	tx.UserRole = NewUserRoleClient(tx.config)
	tx.UserTag = NewUserTagClient(tx.config)
	tx.Webhook = NewWebhookClient(tx.config)
}

// txDriver wraps the given dialect.Tx with a nop dialect.Driver implementation.
// The idea is to support transactions without adding any extra code to the builders.
// When a builder calls to driver.Tx(), it gets the same dialect.Tx instance.
// Commit and Rollback are nop for the internal builders and the user must call one
// of them in order to commit or rollback the transaction.
//
// If a closed transaction is embedded in one of the generated entities, and the entity
// applies a query, for example: Api.QueryXXX(), the query will be executed
// through the driver which created this transaction.
//
// Note that txDriver is not goroutine safe.
type txDriver struct {
	// the driver we started the transaction from.
	drv dialect.Driver
	// tx is the underlying transaction.
	tx dialect.Tx
	// completion hooks.
	mu         sync.Mutex
	onCommit   []CommitHook
	onRollback []RollbackHook
}

// newTx creates a new transactional driver.
func newTx(ctx context.Context, drv dialect.Driver) (*txDriver, error) {
	tx, err := drv.Tx(ctx)
	if err != nil {
		return nil, err
	}
	return &txDriver{tx: tx, drv: drv}, nil
}

// Tx returns the transaction wrapper (txDriver) to avoid Commit or Rollback calls
// from the internal builders. Should be called only by the internal builders.
func (tx *txDriver) Tx(context.Context) (dialect.Tx, error) { return tx, nil }

// Dialect returns the dialect of the driver we started the transaction from.
func (tx *txDriver) Dialect() string { return tx.drv.Dialect() }

// Close is a nop close.
func (*txDriver) Close() error { return nil }

// Commit is a nop commit for the internal builders.
// User must call `Tx.Commit` in order to commit the transaction.
func (*txDriver) Commit() error { return nil }

// Rollback is a nop rollback for the internal builders.
// User must call `Tx.Rollback` in order to rollback the transaction.
func (*txDriver) Rollback() error { return nil }

// Exec calls tx.Exec.
func (tx *txDriver) Exec(ctx context.Context, query string, args, v any) error {
	return tx.tx.Exec(ctx, query, args, v)
}

// Query calls tx.Query.
func (tx *txDriver) Query(ctx context.Context, query string, args, v any) error {
	return tx.tx.Query(ctx, query, args, v)
}

var _ dialect.Driver = (*txDriver)(nil)
