// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-uba/app/core/service/internal/data/ent/usertag"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 用户标签关联表
type UserTag struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 业务用户ID
	UserID *uint32 `json:"user_id,omitempty"`
	// 标签定义ID，关联 uba_tag_definitions.id
	TagID *uint32 `json:"tag_id,omitempty"`
	// 标签值，实际存储值
	TagValue string `json:"tag_value,omitempty"`
	// 显示名称
	ValueLabel *string `json:"value_label,omitempty"`
	// 置信度，算法打标
	Confidence float64 `json:"confidence,omitempty"`
	// 来源：manual/rule/model/import
	Source string `json:"source,omitempty"`
	// 来源规则ID，关联规则表
	SourceRuleID *uint32 `json:"source_rule_id,omitempty"`
	// 生效时间
	EffectiveTime *time.Time `json:"effective_time,omitempty"`
	// 过期时间，NULL表示永久
	ExpireTime *time.Time `json:"expire_time,omitempty"`
	// 是否激活，1为激活，0为未激活
	IsActive     bool `json:"is_active,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usertag.FieldIsActive:
			values[i] = new(sql.NullBool)
		case usertag.FieldConfidence:
			values[i] = new(sql.NullFloat64)
		case usertag.FieldID, usertag.FieldTenantID, usertag.FieldCreatedBy, usertag.FieldUpdatedBy, usertag.FieldDeletedBy, usertag.FieldUserID, usertag.FieldTagID, usertag.FieldSourceRuleID:
			values[i] = new(sql.NullInt64)
		case usertag.FieldTagValue, usertag.FieldValueLabel, usertag.FieldSource:
			values[i] = new(sql.NullString)
		case usertag.FieldCreatedAt, usertag.FieldUpdatedAt, usertag.FieldDeletedAt, usertag.FieldEffectiveTime, usertag.FieldExpireTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserTag fields.
func (_m *UserTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usertag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case usertag.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case usertag.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case usertag.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case usertag.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case usertag.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case usertag.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case usertag.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case usertag.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uint32)
				*_m.UserID = uint32(value.Int64)
			}
		case usertag.FieldTagID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tag_id", values[i])
			} else if value.Valid {
				_m.TagID = new(uint32)
				*_m.TagID = uint32(value.Int64)
			}
		case usertag.FieldTagValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag_value", values[i])
			} else if value.Valid {
				_m.TagValue = value.String
			}
		case usertag.FieldValueLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value_label", values[i])
			} else if value.Valid {
				_m.ValueLabel = new(string)
				*_m.ValueLabel = value.String
			}
		case usertag.FieldConfidence:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[i])
			} else if value.Valid {
				_m.Confidence = value.Float64
			}
		case usertag.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case usertag.FieldSourceRuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_rule_id", values[i])
			} else if value.Valid {
				_m.SourceRuleID = new(uint32)
				*_m.SourceRuleID = uint32(value.Int64)
			}
		case usertag.FieldEffectiveTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_time", values[i])
			} else if value.Valid {
				_m.EffectiveTime = new(time.Time)
				*_m.EffectiveTime = value.Time
			}
		case usertag.FieldExpireTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expire_time", values[i])
			} else if value.Valid {
				_m.ExpireTime = new(time.Time)
				*_m.ExpireTime = value.Time
			}
		case usertag.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserTag.
// This includes values selected through modifiers, order, etc.
func (_m *UserTag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserTag.
// Note that you need to call UserTag.Unwrap() before calling this method if this UserTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserTag) Update() *UserTagUpdateOne {
	return NewUserTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserTag) Unwrap() *UserTag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserTag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserTag) String() string {
	var builder strings.Builder
	builder.WriteString("UserTag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TagID; v != nil {
		builder.WriteString("tag_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("tag_value=")
	builder.WriteString(_m.TagValue)
	builder.WriteString(", ")
	if v := _m.ValueLabel; v != nil {
		builder.WriteString("value_label=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Confidence))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.SourceRuleID; v != nil {
		builder.WriteString("source_rule_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.EffectiveTime; v != nil {
		builder.WriteString("effective_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpireTime; v != nil {
		builder.WriteString("expire_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// UserTags is a parsable slice of UserTag.
type UserTags []*UserTag
