// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	servicev1 "go-wind-uba/api/gen/go/uba/service/v1"
	"go-wind-uba/app/core/service/internal/data/ent/predicate"
	"go-wind-uba/app/core/service/internal/data/ent/webhook"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// WebhookUpdate is the builder for updating Webhook entities.
type WebhookUpdate struct {
	config
	hooks     []Hook
	mutation  *WebhookMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the WebhookUpdate builder.
func (_u *WebhookUpdate) Where(ps ...predicate.Webhook) *WebhookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WebhookUpdate) SetUpdatedAt(v time.Time) *WebhookUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableUpdatedAt(v *time.Time) *WebhookUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *WebhookUpdate) ClearUpdatedAt() *WebhookUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WebhookUpdate) SetDeletedAt(v time.Time) *WebhookUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableDeletedAt(v *time.Time) *WebhookUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WebhookUpdate) ClearDeletedAt() *WebhookUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *WebhookUpdate) SetCreatedBy(v uint32) *WebhookUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableCreatedBy(v *uint32) *WebhookUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *WebhookUpdate) AddCreatedBy(v int32) *WebhookUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *WebhookUpdate) ClearCreatedBy() *WebhookUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *WebhookUpdate) SetUpdatedBy(v uint32) *WebhookUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableUpdatedBy(v *uint32) *WebhookUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *WebhookUpdate) AddUpdatedBy(v int32) *WebhookUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *WebhookUpdate) ClearUpdatedBy() *WebhookUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *WebhookUpdate) SetDeletedBy(v uint32) *WebhookUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableDeletedBy(v *uint32) *WebhookUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *WebhookUpdate) AddDeletedBy(v int32) *WebhookUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *WebhookUpdate) ClearDeletedBy() *WebhookUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *WebhookUpdate) SetName(v string) *WebhookUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableName(v *string) *WebhookUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *WebhookUpdate) ClearName() *WebhookUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetURL sets the "url" field.
func (_u *WebhookUpdate) SetURL(v string) *WebhookUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableURL(v *string) *WebhookUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *WebhookUpdate) ClearURL() *WebhookUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetSecret sets the "secret" field.
func (_u *WebhookUpdate) SetSecret(v string) *WebhookUpdate {
	_u.mutation.SetSecret(v)
	return _u
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableSecret(v *string) *WebhookUpdate {
	if v != nil {
		_u.SetSecret(*v)
	}
	return _u
}

// ClearSecret clears the value of the "secret" field.
func (_u *WebhookUpdate) ClearSecret() *WebhookUpdate {
	_u.mutation.ClearSecret()
	return _u
}

// SetEventTypes sets the "event_types" field.
func (_u *WebhookUpdate) SetEventTypes(v []string) *WebhookUpdate {
	_u.mutation.SetEventTypes(v)
	return _u
}

// AppendEventTypes appends value to the "event_types" field.
func (_u *WebhookUpdate) AppendEventTypes(v []string) *WebhookUpdate {
	_u.mutation.AppendEventTypes(v)
	return _u
}

// ClearEventTypes clears the value of the "event_types" field.
func (_u *WebhookUpdate) ClearEventTypes() *WebhookUpdate {
	_u.mutation.ClearEventTypes()
	return _u
}

// SetFilter sets the "filter" field.
func (_u *WebhookUpdate) SetFilter(v *servicev1.WebhookFilter) *WebhookUpdate {
	_u.mutation.SetFilter(v)
	return _u
}

// ClearFilter clears the value of the "filter" field.
func (_u *WebhookUpdate) ClearFilter() *WebhookUpdate {
	_u.mutation.ClearFilter()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WebhookUpdate) SetEnabled(v bool) *WebhookUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableEnabled(v *bool) *WebhookUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_u *WebhookUpdate) SetLastTriggeredAt(v time.Time) *WebhookUpdate {
	_u.mutation.SetLastTriggeredAt(v)
	return _u
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableLastTriggeredAt(v *time.Time) *WebhookUpdate {
	if v != nil {
		_u.SetLastTriggeredAt(*v)
	}
	return _u
}

// ClearLastTriggeredAt clears the value of the "last_triggered_at" field.
func (_u *WebhookUpdate) ClearLastTriggeredAt() *WebhookUpdate {
	_u.mutation.ClearLastTriggeredAt()
	return _u
}

// SetFailureCount sets the "failure_count" field.
func (_u *WebhookUpdate) SetFailureCount(v uint32) *WebhookUpdate {
	_u.mutation.ResetFailureCount()
	_u.mutation.SetFailureCount(v)
	return _u
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableFailureCount(v *uint32) *WebhookUpdate {
	if v != nil {
		_u.SetFailureCount(*v)
	}
	return _u
}

// AddFailureCount adds value to the "failure_count" field.
func (_u *WebhookUpdate) AddFailureCount(v int32) *WebhookUpdate {
	_u.mutation.AddFailureCount(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *WebhookUpdate) SetAppID(v uint32) *WebhookUpdate {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *WebhookUpdate) SetNillableAppID(v *uint32) *WebhookUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *WebhookUpdate) AddAppID(v int32) *WebhookUpdate {
	_u.mutation.AddAppID(v)
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *WebhookUpdate) ClearAppID() *WebhookUpdate {
	_u.mutation.ClearAppID()
	return _u
}

// Mutation returns the WebhookMutation object of the builder.
func (_u *WebhookUpdate) Mutation() *WebhookMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WebhookUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebhookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WebhookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebhookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebhookUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := webhook.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Webhook.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := webhook.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Webhook.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filter(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "filter", err: fmt.Errorf(`ent: validator failed for field "Webhook.filter": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WebhookUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WebhookUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *WebhookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webhook.Table, webhook.Columns, sqlgraph.NewFieldSpec(webhook.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(webhook.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(webhook.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(webhook.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(webhook.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(webhook.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(webhook.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(webhook.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(webhook.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(webhook.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(webhook.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(webhook.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(webhook.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(webhook.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(webhook.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(webhook.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(webhook.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(webhook.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(webhook.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(webhook.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(webhook.FieldSecret, field.TypeString, value)
	}
	if _u.mutation.SecretCleared() {
		_spec.ClearField(webhook.FieldSecret, field.TypeString)
	}
	if value, ok := _u.mutation.EventTypes(); ok {
		_spec.SetField(webhook.FieldEventTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEventTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, webhook.FieldEventTypes, value)
		})
	}
	if _u.mutation.EventTypesCleared() {
		_spec.ClearField(webhook.FieldEventTypes, field.TypeJSON)
	}
	if value, ok := _u.mutation.Filter(); ok {
		_spec.SetField(webhook.FieldFilter, field.TypeJSON, value)
	}
	if _u.mutation.FilterCleared() {
		_spec.ClearField(webhook.FieldFilter, field.TypeJSON)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(webhook.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastTriggeredAt(); ok {
		_spec.SetField(webhook.FieldLastTriggeredAt, field.TypeTime, value)
	}
	if _u.mutation.LastTriggeredAtCleared() {
		_spec.ClearField(webhook.FieldLastTriggeredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureCount(); ok {
		_spec.SetField(webhook.FieldFailureCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedFailureCount(); ok {
		_spec.AddField(webhook.FieldFailureCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(webhook.FieldAppID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(webhook.FieldAppID, field.TypeUint32, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(webhook.FieldAppID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhook.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WebhookUpdateOne is the builder for updating a single Webhook entity.
type WebhookUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *WebhookMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WebhookUpdateOne) SetUpdatedAt(v time.Time) *WebhookUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableUpdatedAt(v *time.Time) *WebhookUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *WebhookUpdateOne) ClearUpdatedAt() *WebhookUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WebhookUpdateOne) SetDeletedAt(v time.Time) *WebhookUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableDeletedAt(v *time.Time) *WebhookUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WebhookUpdateOne) ClearDeletedAt() *WebhookUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *WebhookUpdateOne) SetCreatedBy(v uint32) *WebhookUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableCreatedBy(v *uint32) *WebhookUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *WebhookUpdateOne) AddCreatedBy(v int32) *WebhookUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *WebhookUpdateOne) ClearCreatedBy() *WebhookUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *WebhookUpdateOne) SetUpdatedBy(v uint32) *WebhookUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableUpdatedBy(v *uint32) *WebhookUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *WebhookUpdateOne) AddUpdatedBy(v int32) *WebhookUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *WebhookUpdateOne) ClearUpdatedBy() *WebhookUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *WebhookUpdateOne) SetDeletedBy(v uint32) *WebhookUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableDeletedBy(v *uint32) *WebhookUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *WebhookUpdateOne) AddDeletedBy(v int32) *WebhookUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *WebhookUpdateOne) ClearDeletedBy() *WebhookUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *WebhookUpdateOne) SetName(v string) *WebhookUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableName(v *string) *WebhookUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *WebhookUpdateOne) ClearName() *WebhookUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetURL sets the "url" field.
func (_u *WebhookUpdateOne) SetURL(v string) *WebhookUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableURL(v *string) *WebhookUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *WebhookUpdateOne) ClearURL() *WebhookUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetSecret sets the "secret" field.
func (_u *WebhookUpdateOne) SetSecret(v string) *WebhookUpdateOne {
	_u.mutation.SetSecret(v)
	return _u
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableSecret(v *string) *WebhookUpdateOne {
	if v != nil {
		_u.SetSecret(*v)
	}
	return _u
}

// ClearSecret clears the value of the "secret" field.
func (_u *WebhookUpdateOne) ClearSecret() *WebhookUpdateOne {
	_u.mutation.ClearSecret()
	return _u
}

// SetEventTypes sets the "event_types" field.
func (_u *WebhookUpdateOne) SetEventTypes(v []string) *WebhookUpdateOne {
	_u.mutation.SetEventTypes(v)
	return _u
}

// AppendEventTypes appends value to the "event_types" field.
func (_u *WebhookUpdateOne) AppendEventTypes(v []string) *WebhookUpdateOne {
	_u.mutation.AppendEventTypes(v)
	return _u
}

// ClearEventTypes clears the value of the "event_types" field.
func (_u *WebhookUpdateOne) ClearEventTypes() *WebhookUpdateOne {
	_u.mutation.ClearEventTypes()
	return _u
}

// SetFilter sets the "filter" field.
func (_u *WebhookUpdateOne) SetFilter(v *servicev1.WebhookFilter) *WebhookUpdateOne {
	_u.mutation.SetFilter(v)
	return _u
}

// ClearFilter clears the value of the "filter" field.
func (_u *WebhookUpdateOne) ClearFilter() *WebhookUpdateOne {
	_u.mutation.ClearFilter()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WebhookUpdateOne) SetEnabled(v bool) *WebhookUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableEnabled(v *bool) *WebhookUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_u *WebhookUpdateOne) SetLastTriggeredAt(v time.Time) *WebhookUpdateOne {
	_u.mutation.SetLastTriggeredAt(v)
	return _u
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableLastTriggeredAt(v *time.Time) *WebhookUpdateOne {
	if v != nil {
		_u.SetLastTriggeredAt(*v)
	}
	return _u
}

// ClearLastTriggeredAt clears the value of the "last_triggered_at" field.
func (_u *WebhookUpdateOne) ClearLastTriggeredAt() *WebhookUpdateOne {
	_u.mutation.ClearLastTriggeredAt()
	return _u
}

// SetFailureCount sets the "failure_count" field.
func (_u *WebhookUpdateOne) SetFailureCount(v uint32) *WebhookUpdateOne {
	_u.mutation.ResetFailureCount()
	_u.mutation.SetFailureCount(v)
	return _u
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableFailureCount(v *uint32) *WebhookUpdateOne {
	if v != nil {
		_u.SetFailureCount(*v)
	}
	return _u
}

// AddFailureCount adds value to the "failure_count" field.
func (_u *WebhookUpdateOne) AddFailureCount(v int32) *WebhookUpdateOne {
	_u.mutation.AddFailureCount(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *WebhookUpdateOne) SetAppID(v uint32) *WebhookUpdateOne {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *WebhookUpdateOne) SetNillableAppID(v *uint32) *WebhookUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *WebhookUpdateOne) AddAppID(v int32) *WebhookUpdateOne {
	_u.mutation.AddAppID(v)
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *WebhookUpdateOne) ClearAppID() *WebhookUpdateOne {
	_u.mutation.ClearAppID()
	return _u
}

// Mutation returns the WebhookMutation object of the builder.
func (_u *WebhookUpdateOne) Mutation() *WebhookMutation {
	return _u.mutation
}

// Where appends a list predicates to the WebhookUpdate builder.
func (_u *WebhookUpdateOne) Where(ps ...predicate.Webhook) *WebhookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WebhookUpdateOne) Select(field string, fields ...string) *WebhookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Webhook entity.
func (_u *WebhookUpdateOne) Save(ctx context.Context) (*Webhook, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebhookUpdateOne) SaveX(ctx context.Context) *Webhook {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WebhookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebhookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebhookUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := webhook.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Webhook.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := webhook.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Webhook.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filter(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "filter", err: fmt.Errorf(`ent: validator failed for field "Webhook.filter": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WebhookUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WebhookUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *WebhookUpdateOne) sqlSave(ctx context.Context) (_node *Webhook, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(webhook.Table, webhook.Columns, sqlgraph.NewFieldSpec(webhook.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Webhook.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webhook.FieldID)
		for _, f := range fields {
			if !webhook.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != webhook.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(webhook.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(webhook.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(webhook.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(webhook.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(webhook.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(webhook.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(webhook.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(webhook.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(webhook.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(webhook.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(webhook.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(webhook.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(webhook.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(webhook.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(webhook.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(webhook.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(webhook.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(webhook.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(webhook.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(webhook.FieldSecret, field.TypeString, value)
	}
	if _u.mutation.SecretCleared() {
		_spec.ClearField(webhook.FieldSecret, field.TypeString)
	}
	if value, ok := _u.mutation.EventTypes(); ok {
		_spec.SetField(webhook.FieldEventTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEventTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, webhook.FieldEventTypes, value)
		})
	}
	if _u.mutation.EventTypesCleared() {
		_spec.ClearField(webhook.FieldEventTypes, field.TypeJSON)
	}
	if value, ok := _u.mutation.Filter(); ok {
		_spec.SetField(webhook.FieldFilter, field.TypeJSON, value)
	}
	if _u.mutation.FilterCleared() {
		_spec.ClearField(webhook.FieldFilter, field.TypeJSON)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(webhook.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastTriggeredAt(); ok {
		_spec.SetField(webhook.FieldLastTriggeredAt, field.TypeTime, value)
	}
	if _u.mutation.LastTriggeredAtCleared() {
		_spec.ClearField(webhook.FieldLastTriggeredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureCount(); ok {
		_spec.SetField(webhook.FieldFailureCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedFailureCount(); ok {
		_spec.AddField(webhook.FieldFailureCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(webhook.FieldAppID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(webhook.FieldAppID, field.TypeUint32, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(webhook.FieldAppID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Webhook{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{webhook.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
