// Code generated by ent, DO NOT EDIT.

package riskruleversion

import (
	"go-wind-uba/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldDeletedBy, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldVersion, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldTenantID, v))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldRuleID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldName, v))
}

// RuleExpression applies equality check predicate on the "rule_expression" field. It's identical to RuleExpressionEQ.
func RuleExpression(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldRuleExpression, v))
}

// RiskLevel applies equality check predicate on the "risk_level" field. It's identical to RiskLevelEQ.
func RiskLevel(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldRiskLevel, v))
}

// ChangeSummary applies equality check predicate on the "change_summary" field. It's identical to ChangeSummaryEQ.
func ChangeSummary(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldChangeSummary, v))
}

// ChangeReason applies equality check predicate on the "change_reason" field. It's identical to ChangeReasonEQ.
func ChangeReason(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldChangeReason, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedBy applies equality check predicate on the "published_by" field. It's identical to PublishedByEQ.
func PublishedBy(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldPublishedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldDeletedBy))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldVersion, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldTenantID))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldRuleID, vs...))
}

// RuleIDGT applies the GT predicate on the "rule_id" field.
func RuleIDGT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldRuleID, v))
}

// RuleIDGTE applies the GTE predicate on the "rule_id" field.
func RuleIDGTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldRuleID, v))
}

// RuleIDLT applies the LT predicate on the "rule_id" field.
func RuleIDLT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldRuleID, v))
}

// RuleIDLTE applies the LTE predicate on the "rule_id" field.
func RuleIDLTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldRuleID, v))
}

// RuleIDIsNil applies the IsNil predicate on the "rule_id" field.
func RuleIDIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldRuleID))
}

// RuleIDNotNil applies the NotNil predicate on the "rule_id" field.
func RuleIDNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldRuleID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldContainsFold(FieldName, v))
}

// RuleExpressionEQ applies the EQ predicate on the "rule_expression" field.
func RuleExpressionEQ(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldRuleExpression, v))
}

// RuleExpressionNEQ applies the NEQ predicate on the "rule_expression" field.
func RuleExpressionNEQ(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldRuleExpression, v))
}

// RuleExpressionIn applies the In predicate on the "rule_expression" field.
func RuleExpressionIn(vs ...string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldRuleExpression, vs...))
}

// RuleExpressionNotIn applies the NotIn predicate on the "rule_expression" field.
func RuleExpressionNotIn(vs ...string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldRuleExpression, vs...))
}

// RuleExpressionGT applies the GT predicate on the "rule_expression" field.
func RuleExpressionGT(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldRuleExpression, v))
}

// RuleExpressionGTE applies the GTE predicate on the "rule_expression" field.
func RuleExpressionGTE(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldRuleExpression, v))
}

// RuleExpressionLT applies the LT predicate on the "rule_expression" field.
func RuleExpressionLT(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldRuleExpression, v))
}

// RuleExpressionLTE applies the LTE predicate on the "rule_expression" field.
func RuleExpressionLTE(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldRuleExpression, v))
}

// RuleExpressionContains applies the Contains predicate on the "rule_expression" field.
func RuleExpressionContains(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldContains(FieldRuleExpression, v))
}

// RuleExpressionHasPrefix applies the HasPrefix predicate on the "rule_expression" field.
func RuleExpressionHasPrefix(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldHasPrefix(FieldRuleExpression, v))
}

// RuleExpressionHasSuffix applies the HasSuffix predicate on the "rule_expression" field.
func RuleExpressionHasSuffix(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldHasSuffix(FieldRuleExpression, v))
}

// RuleExpressionEqualFold applies the EqualFold predicate on the "rule_expression" field.
func RuleExpressionEqualFold(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEqualFold(FieldRuleExpression, v))
}

// RuleExpressionContainsFold applies the ContainsFold predicate on the "rule_expression" field.
func RuleExpressionContainsFold(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldContainsFold(FieldRuleExpression, v))
}

// RiskLevelEQ applies the EQ predicate on the "risk_level" field.
func RiskLevelEQ(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldRiskLevel, v))
}

// RiskLevelNEQ applies the NEQ predicate on the "risk_level" field.
func RiskLevelNEQ(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldRiskLevel, v))
}

// RiskLevelIn applies the In predicate on the "risk_level" field.
func RiskLevelIn(vs ...string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldRiskLevel, vs...))
}

// RiskLevelNotIn applies the NotIn predicate on the "risk_level" field.
func RiskLevelNotIn(vs ...string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldRiskLevel, vs...))
}

// RiskLevelGT applies the GT predicate on the "risk_level" field.
func RiskLevelGT(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldRiskLevel, v))
}

// RiskLevelGTE applies the GTE predicate on the "risk_level" field.
func RiskLevelGTE(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldRiskLevel, v))
}

// RiskLevelLT applies the LT predicate on the "risk_level" field.
func RiskLevelLT(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldRiskLevel, v))
}

// RiskLevelLTE applies the LTE predicate on the "risk_level" field.
func RiskLevelLTE(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldRiskLevel, v))
}

// RiskLevelContains applies the Contains predicate on the "risk_level" field.
func RiskLevelContains(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldContains(FieldRiskLevel, v))
}

// RiskLevelHasPrefix applies the HasPrefix predicate on the "risk_level" field.
func RiskLevelHasPrefix(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldHasPrefix(FieldRiskLevel, v))
}

// RiskLevelHasSuffix applies the HasSuffix predicate on the "risk_level" field.
func RiskLevelHasSuffix(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldHasSuffix(FieldRiskLevel, v))
}

// RiskLevelIsNil applies the IsNil predicate on the "risk_level" field.
func RiskLevelIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldRiskLevel))
}

// RiskLevelNotNil applies the NotNil predicate on the "risk_level" field.
func RiskLevelNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldRiskLevel))
}

// RiskLevelEqualFold applies the EqualFold predicate on the "risk_level" field.
func RiskLevelEqualFold(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEqualFold(FieldRiskLevel, v))
}

// RiskLevelContainsFold applies the ContainsFold predicate on the "risk_level" field.
func RiskLevelContainsFold(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldContainsFold(FieldRiskLevel, v))
}

// ChangeSummaryEQ applies the EQ predicate on the "change_summary" field.
func ChangeSummaryEQ(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldChangeSummary, v))
}

// ChangeSummaryNEQ applies the NEQ predicate on the "change_summary" field.
func ChangeSummaryNEQ(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldChangeSummary, v))
}

// ChangeSummaryIn applies the In predicate on the "change_summary" field.
func ChangeSummaryIn(vs ...string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldChangeSummary, vs...))
}

// ChangeSummaryNotIn applies the NotIn predicate on the "change_summary" field.
func ChangeSummaryNotIn(vs ...string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldChangeSummary, vs...))
}

// ChangeSummaryGT applies the GT predicate on the "change_summary" field.
func ChangeSummaryGT(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldChangeSummary, v))
}

// ChangeSummaryGTE applies the GTE predicate on the "change_summary" field.
func ChangeSummaryGTE(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldChangeSummary, v))
}

// ChangeSummaryLT applies the LT predicate on the "change_summary" field.
func ChangeSummaryLT(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldChangeSummary, v))
}

// ChangeSummaryLTE applies the LTE predicate on the "change_summary" field.
func ChangeSummaryLTE(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldChangeSummary, v))
}

// ChangeSummaryContains applies the Contains predicate on the "change_summary" field.
func ChangeSummaryContains(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldContains(FieldChangeSummary, v))
}

// ChangeSummaryHasPrefix applies the HasPrefix predicate on the "change_summary" field.
func ChangeSummaryHasPrefix(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldHasPrefix(FieldChangeSummary, v))
}

// ChangeSummaryHasSuffix applies the HasSuffix predicate on the "change_summary" field.
func ChangeSummaryHasSuffix(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldHasSuffix(FieldChangeSummary, v))
}

// ChangeSummaryIsNil applies the IsNil predicate on the "change_summary" field.
func ChangeSummaryIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldChangeSummary))
}

// ChangeSummaryNotNil applies the NotNil predicate on the "change_summary" field.
func ChangeSummaryNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldChangeSummary))
}

// ChangeSummaryEqualFold applies the EqualFold predicate on the "change_summary" field.
func ChangeSummaryEqualFold(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEqualFold(FieldChangeSummary, v))
}

// ChangeSummaryContainsFold applies the ContainsFold predicate on the "change_summary" field.
func ChangeSummaryContainsFold(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldContainsFold(FieldChangeSummary, v))
}

// ChangeReasonEQ applies the EQ predicate on the "change_reason" field.
func ChangeReasonEQ(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldChangeReason, v))
}

// ChangeReasonNEQ applies the NEQ predicate on the "change_reason" field.
func ChangeReasonNEQ(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldChangeReason, v))
}

// ChangeReasonIn applies the In predicate on the "change_reason" field.
func ChangeReasonIn(vs ...string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldChangeReason, vs...))
}

// ChangeReasonNotIn applies the NotIn predicate on the "change_reason" field.
func ChangeReasonNotIn(vs ...string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldChangeReason, vs...))
}

// ChangeReasonGT applies the GT predicate on the "change_reason" field.
func ChangeReasonGT(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldChangeReason, v))
}

// ChangeReasonGTE applies the GTE predicate on the "change_reason" field.
func ChangeReasonGTE(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldChangeReason, v))
}

// ChangeReasonLT applies the LT predicate on the "change_reason" field.
func ChangeReasonLT(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldChangeReason, v))
}

// ChangeReasonLTE applies the LTE predicate on the "change_reason" field.
func ChangeReasonLTE(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldChangeReason, v))
}

// ChangeReasonContains applies the Contains predicate on the "change_reason" field.
func ChangeReasonContains(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldContains(FieldChangeReason, v))
}

// ChangeReasonHasPrefix applies the HasPrefix predicate on the "change_reason" field.
func ChangeReasonHasPrefix(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldHasPrefix(FieldChangeReason, v))
}

// ChangeReasonHasSuffix applies the HasSuffix predicate on the "change_reason" field.
func ChangeReasonHasSuffix(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldHasSuffix(FieldChangeReason, v))
}

// ChangeReasonIsNil applies the IsNil predicate on the "change_reason" field.
func ChangeReasonIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldChangeReason))
}

// ChangeReasonNotNil applies the NotNil predicate on the "change_reason" field.
func ChangeReasonNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldChangeReason))
}

// ChangeReasonEqualFold applies the EqualFold predicate on the "change_reason" field.
func ChangeReasonEqualFold(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEqualFold(FieldChangeReason, v))
}

// ChangeReasonContainsFold applies the ContainsFold predicate on the "change_reason" field.
func ChangeReasonContainsFold(v string) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldContainsFold(FieldChangeReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldStatus, vs...))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldPublishedAt))
}

// PublishedByEQ applies the EQ predicate on the "published_by" field.
func PublishedByEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldEQ(FieldPublishedBy, v))
}

// PublishedByNEQ applies the NEQ predicate on the "published_by" field.
func PublishedByNEQ(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNEQ(FieldPublishedBy, v))
}

// PublishedByIn applies the In predicate on the "published_by" field.
func PublishedByIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIn(FieldPublishedBy, vs...))
}

// PublishedByNotIn applies the NotIn predicate on the "published_by" field.
func PublishedByNotIn(vs ...uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotIn(FieldPublishedBy, vs...))
}

// PublishedByGT applies the GT predicate on the "published_by" field.
func PublishedByGT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGT(FieldPublishedBy, v))
}

// PublishedByGTE applies the GTE predicate on the "published_by" field.
func PublishedByGTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldGTE(FieldPublishedBy, v))
}

// PublishedByLT applies the LT predicate on the "published_by" field.
func PublishedByLT(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLT(FieldPublishedBy, v))
}

// PublishedByLTE applies the LTE predicate on the "published_by" field.
func PublishedByLTE(v uint32) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldLTE(FieldPublishedBy, v))
}

// PublishedByIsNil applies the IsNil predicate on the "published_by" field.
func PublishedByIsNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldIsNull(FieldPublishedBy))
}

// PublishedByNotNil applies the NotNil predicate on the "published_by" field.
func PublishedByNotNil() predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.FieldNotNull(FieldPublishedBy))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RiskRuleVersion) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RiskRuleVersion) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RiskRuleVersion) predicate.RiskRuleVersion {
	return predicate.RiskRuleVersion(sql.NotPredicates(p))
}
