// Code generated by ent, DO NOT EDIT.

package riskrule

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the riskrule type in the database.
	Label = "risk_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldRiskType holds the string denoting the risk_type field in the database.
	FieldRiskType = "risk_type"
	// FieldDefaultLevel holds the string denoting the default_level field in the database.
	FieldDefaultLevel = "default_level"
	// FieldCondition holds the string denoting the condition field in the database.
	FieldCondition = "condition"
	// FieldActions holds the string denoting the actions field in the database.
	FieldActions = "actions"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldRuleExpression holds the string denoting the rule_expression field in the database.
	FieldRuleExpression = "rule_expression"
	// FieldRuleConfig holds the string denoting the rule_config field in the database.
	FieldRuleConfig = "rule_config"
	// FieldExecMode holds the string denoting the exec_mode field in the database.
	FieldExecMode = "exec_mode"
	// FieldTriggerCount holds the string denoting the trigger_count field in the database.
	FieldTriggerCount = "trigger_count"
	// FieldLastTriggeredAt holds the string denoting the last_triggered_at field in the database.
	FieldLastTriggeredAt = "last_triggered_at"
	// Table holds the table name of the riskrule in the database.
	Table = "uba_risk_rules"
)

// Columns holds all SQL columns for riskrule fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldTenantID,
	FieldName,
	FieldDescription,
	FieldRiskType,
	FieldDefaultLevel,
	FieldCondition,
	FieldActions,
	FieldEnabled,
	FieldPriority,
	FieldCode,
	FieldRuleExpression,
	FieldRuleConfig,
	FieldExecMode,
	FieldTriggerCount,
	FieldLastTriggeredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-wind-uba/app/core/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority uint32
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultTriggerCount holds the default value on creation for the "trigger_count" field.
	DefaultTriggerCount uint64
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// RiskType defines the type for the "risk_type" enum field.
type RiskType string

// RiskType values.
const (
	RiskTypeRiskTypeLoginAnomaly       RiskType = "RISK_TYPE_LOGIN_ANOMALY"
	RiskTypeRiskTypeBruteForce         RiskType = "RISK_TYPE_BRUTE_FORCE"
	RiskTypeRiskTypeCredentialStuffing RiskType = "RISK_TYPE_CREDENTIAL_STUFFING"
	RiskTypeRiskTypeFrequentOperation  RiskType = "RISK_TYPE_FREQUENT_OPERATION"
	RiskTypeRiskTypeAbnormalFlow       RiskType = "RISK_TYPE_ABNORMAL_FLOW"
	RiskTypeRiskTypeDataExfiltration   RiskType = "RISK_TYPE_DATA_EXFILTRATION"
	RiskTypeRiskTypeDeviceChange       RiskType = "RISK_TYPE_DEVICE_CHANGE"
	RiskTypeRiskTypeLocationAnomaly    RiskType = "RISK_TYPE_LOCATION_ANOMALY"
	RiskTypeRiskTypeProxyDetected      RiskType = "RISK_TYPE_PROXY_DETECTED"
	RiskTypeRiskTypeFraudPayment       RiskType = "RISK_TYPE_FRAUD_PAYMENT"
	RiskTypeRiskTypeAbusePromotion     RiskType = "RISK_TYPE_ABUSE_PROMOTION"
)

func (rt RiskType) String() string {
	return string(rt)
}

// RiskTypeValidator is a validator for the "risk_type" field enum values. It is called by the builders before save.
func RiskTypeValidator(rt RiskType) error {
	switch rt {
	case RiskTypeRiskTypeLoginAnomaly, RiskTypeRiskTypeBruteForce, RiskTypeRiskTypeCredentialStuffing, RiskTypeRiskTypeFrequentOperation, RiskTypeRiskTypeAbnormalFlow, RiskTypeRiskTypeDataExfiltration, RiskTypeRiskTypeDeviceChange, RiskTypeRiskTypeLocationAnomaly, RiskTypeRiskTypeProxyDetected, RiskTypeRiskTypeFraudPayment, RiskTypeRiskTypeAbusePromotion:
		return nil
	default:
		return fmt.Errorf("riskrule: invalid enum value for risk_type field: %q", rt)
	}
}

// DefaultLevel defines the type for the "default_level" enum field.
type DefaultLevel string

// DefaultLevel values.
const (
	DefaultLevelRiskLevelNormal     DefaultLevel = "RISK_LEVEL_NORMAL"
	DefaultLevelRiskLevelSuspicious DefaultLevel = "RISK_LEVEL_SUSPICIOUS"
	DefaultLevelRiskLevelHigh       DefaultLevel = "RISK_LEVEL_HIGH"
	DefaultLevelRiskLevelCritical   DefaultLevel = "RISK_LEVEL_CRITICAL"
)

func (dl DefaultLevel) String() string {
	return string(dl)
}

// DefaultLevelValidator is a validator for the "default_level" field enum values. It is called by the builders before save.
func DefaultLevelValidator(dl DefaultLevel) error {
	switch dl {
	case DefaultLevelRiskLevelNormal, DefaultLevelRiskLevelSuspicious, DefaultLevelRiskLevelHigh, DefaultLevelRiskLevelCritical:
		return nil
	default:
		return fmt.Errorf("riskrule: invalid enum value for default_level field: %q", dl)
	}
}

// ExecMode defines the type for the "exec_mode" enum field.
type ExecMode string

// ExecModeRealtime is the default value of the ExecMode enum.
const DefaultExecMode = ExecModeRealtime

// ExecMode values.
const (
	ExecModeRealtime ExecMode = "REALTIME"
	ExecModeBatch    ExecMode = "BATCH"
)

func (em ExecMode) String() string {
	return string(em)
}

// ExecModeValidator is a validator for the "exec_mode" field enum values. It is called by the builders before save.
func ExecModeValidator(em ExecMode) error {
	switch em {
	case ExecModeRealtime, ExecModeBatch:
		return nil
	default:
		return fmt.Errorf("riskrule: invalid enum value for exec_mode field: %q", em)
	}
}

// OrderOption defines the ordering options for the RiskRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByRiskType orders the results by the risk_type field.
func ByRiskType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRiskType, opts...).ToFunc()
}

// ByDefaultLevel orders the results by the default_level field.
func ByDefaultLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultLevel, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByRuleExpression orders the results by the rule_expression field.
func ByRuleExpression(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleExpression, opts...).ToFunc()
}

// ByExecMode orders the results by the exec_mode field.
func ByExecMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecMode, opts...).ToFunc()
}

// ByTriggerCount orders the results by the trigger_count field.
func ByTriggerCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerCount, opts...).ToFunc()
}

// ByLastTriggeredAt orders the results by the last_triggered_at field.
func ByLastTriggeredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTriggeredAt, opts...).ToFunc()
}
