oss:
  minio:
    endpoint: "127.0.0.1:9001"
    upload_host: "127.0.0.1:9001"
    download_host: "http://127.0.0.1:9001"
    access_key: "root"
    secret_key: "*Abcd123456"
    token: ""
    use_ssl: false